.circleci/config.yml, WORKSPACE, include/nighthawk/common/statistic.h, source/common/frequency.h, source/common/statistic_impl.cc, source/common/statistic_impl.h, test/statistic_test.cc
Updates the Envoy submodule to the latest revision on master, and fixes the build.
=> Update Envoy to the latest

source/server/http_test_server_filter.cc, test/server/http_test_server_filter_integration_test.cc
=> Fix build: move to HeaderString::getStringView()

test/BUILD, test/client_worker_test.cc, test/sequencer_test.cc, test/worker_test.cc
Update Envoy submodule to the latest (plus tweaks to fix NH's build)
=> Update Envoy submodule

.bazelrc, WORKSPACE, ci/do_ci.sh
=> Update Envoy to fix the build that broke as of bazel 0.25

source/client/output_formatter_impl.cc, source/client/output_formatter_impl.h, test/test_data/output_formatter.txt.gold
Improves human-readable output on the CLI
Fixes #69
=> Improve human readable output.

README.md, source/client/options_impl.cc
=> Update README.md & tagline consistency update

bazel/repositories.bzl, source/client/client.cc, source/server/http_test_server_filter.cc, test/client_worker_test.cc, test/worker_test.cc
Update Envoy to cd910bc54f8bbc24061aaeaf666b39422666ee58
=> Envoy dependency tracking update

api/client/options.proto, ci/run_coverage.sh, include/nighthawk/client/benchmark_client.h, include/nighthawk/client/options.h, source/client/benchmark_client_impl.h, source/client/client.cc, source/client/factories_impl.cc, source/client/options_impl.cc, source/client/options_impl.h, source/client/process_impl.cc, source/client/service_impl.cc, source/common/sequencer_impl.cc, source/common/sequencer_impl.h, source/common/utility.cc, source/common/utility.h, test/benchmark_http_client_test.cc, test/factories_test.cc, test/mocks.h, test/options_test.cc, test/output_collector_test.cc, test/sequencer_test.cc, test/utility_test.cc
Opening this PR which has the proposed approach for a single target.
If this looks good I'll push changes for the other candidates, which would follow the pattern here
=> Convert proto interface strings to enums

bazel/repositories.bzl
=> Update HdrHistogram_c 0.9.8 -> 0.9.11

ci/do_ci.sh, source/client/BUILD, source/client/output_collector_impl.cc, source/client/output_collector_impl.h, source/common/BUILD, test/BUILD, test/integration/BUILD, test/integration/test_integration_basics.py, test/statistic_test.cc
Signed-off-by: Harvey Tuch <htuch@google.com>
=> build/test: some fixups/cleanups to support Google import.

README.md
Signed-off-by: John Plevyak <jplevyak@gmail.com>
=> Fix a couple typos.

README.md, ci/do_ci.sh, docs/root/version_history.md, source/client/process_impl.cc, source/client/service_main.h, source/common/uri_impl.cc, source/server/README.md, test/benchmark_http_client_test.cc, test/integration/configurations/nighthawk_http_origin.yaml, test/integration/configurations/nighthawk_https_origin.yaml, test/integration/test_integration_basics.py, test/service_test.cc, test/worker_test.cc
Signed-off-by: Harvey Tuch <htuch@google.com>
=> build: some lint/tidy fixes from Google import.

.bazelrc, bazel/repositories.bzl, source/client/client.cc, source/client/service_impl.cc, source/server/BUILD, source/server/README.md, source/server/http_test_server_filter_config.cc
Updates Envoy to fb8235971792d924a429577f87cd86ea6cbc1a75
=> Update Envoy dependency

include/nighthawk/client/factories.h, include/nighthawk/common/BUILD, include/nighthawk/common/request_source.h, source/client/benchmark_client_impl.h, source/client/client_worker_impl.cc, source/client/client_worker_impl.h, source/client/factories_impl.cc, source/client/factories_impl.h, source/client/process_impl.h, source/client/stream_decoder.h, source/common/BUILD, source/common/request_source_impl.cc, source/common/request_source_impl.h, test/client_worker_test.cc, test/factories_test.cc, test/header_generator_test.cc, test/mocks.cc, test/mocks.h
No functional changes, just a rename.
Split out from #137 to lean that up
=> Rename header source to request source

source/client/output_formatter_impl.cc, test/test_data/output_formatter.medium.fortio.gold
Fixes https://github.com/envoyproxy/nighthawk/issues/182
=> Fortio output: set "labels" field to "Nighthawk"

source/client/options_impl.cc, source/common/platform_util_impl.h
This PR contains 2 commits.
- Fixing build on MAC by linking with the equivalent pthread API on MAC.
- Nit: All exceptions are caught by reference.
=> Minor changes to fix MAC builds.

bazel/repositories.bzl
=> HdrHistogram_c: update from 0.9.12 to 0.9.13

test/BUILD, test/client_worker_test.cc, test/factories_test.cc, test/mocks.cc, test/mocks.h, test/mocks/client/BUILD, test/mocks/client/mock_benchmark_client_factory.cc, test/mocks/client/mock_benchmark_client_factory.h
- No functional changes
- Some small additional cleanup, remove a few unused includes
=> Move MockBenchmarkClientFactory into its own compilation unit

ci/docker/docker_push.sh
=> release prep: push docker image upon tagging

bazel/repositories.bzl, source/server/README.md
=> Update Envoy to ff40a02a838d123f4bf018858c61c983e1c5cce9

source/common/BUILD
=> Add explict dependecy on absl strings

benchmarks/BUILD
=> test: Declare python version for benchmark sources

bazel/repositories.bzl, source/client/benchmark_client_impl.cc
=> Update Envoy to a2ebf092025e64f1b452a8bdaef13795677bceef

.bazelrc, bazel/repositories.bzl
=> Update Envoy to 2a4f7dae855ef81376a8aee6201ea19ea36ef8e2

ci/do_ci.sh
- Experimentally remove one-offs to throttle paralellism
- Eliminate some code duplication
=> Clean up do_ci.sh

source/server/configuration.cc, source/server/configuration.h
=> Source/server/configuration.cc/h: const options arg.

.bazelrc, bazel/repositories.bzl, source/server/README.md
- Update to Envoy 9eeba8fd427d9bd0ef947ec14a3157083cc7bf0e
- Update HdrHistogram_c from 0.11.0 -> 0.11.1
=> Update Envoy & HdrHistogram_c

bazel/repositories.bzl
=> Update Envoy to 5a87f1e59b42ad546698d389f6ccac9406534e17

.bazelrc, bazel/repositories.bzl
=> Update Envoy to b9ed0a991d90363ad04da2191891f54790482dcf

source/common/thread_safe_monotonic_time_stopwatch.h
=> Replace deprecated thread annotations macros.

ci/docker/default-config.yaml, source/server/README.md, test/integration/configurations/nighthawk_http_origin.yaml, test/integration/configurations/nighthawk_http_origin_envoy_deprecated_v2_api.yaml, test/integration/configurations/nighthawk_https_origin.yaml, test/integration/configurations/sni_origin.yaml, test/integration/unit_tests/BUILD
=> Use v3 response headers in configuration

ci/docker/Dockerfile-nighthawk-benchmark
This fixes the broken docker CI workflow.
=> Buming up versions of docker and openrc.

benchmarks/README.md, ci/do_ci.sh, ci/docker/benchmark_build.sh, ci/docker/benchmark_push.sh
Thanks to @mklein for helping out with the dockerhub namespaces.
Fixes #611
=> CI: Push nighthawk-benchmark images

source/adaptive_load/adaptive_load_controller_impl.cc
Logs a stripped down version of the Nighthawk output for each of the short benchmarks.
The output only contains the global result without any statistics.
=> Improve logging done by the adaptive controller.

test/integration/test_integration_basics.py
=> Skip test_http_h1 under sanitizers.

bazel/repositories.bzl, ci/run_envoy_docker.sh
- No code changes
- No .bazelrc change: Latest commit 2ba5bed 11 days ago
=> Update Envoy to e85a7f4 (Aug 10, 2021)

source/client/output_formatter_impl.cc, test/output_formatter_test.cc
=> Simplifying calculation of connections for Fortio.

test/BUILD
=> Adding missing dependencies for process_bootstrap_test.

MAINTAINERS.md
=> Noting that documentation update should be done on every Envoy update.

bazel/repositories.bzl
=> Update Envoy to 129a9f1 (Sep 13, 2021)

source/common/termination_predicate_impl.h
=> Fix bad import.

bazel/repositories.bzl
- updated bazel/repositories.bzl
- .bazelrc already in sync
- no code changes
=> Update Envoy to 70a5f29

.circleci/config.yml
=> Some typo fixes

test/run_nighthawk_bazel_coverage.sh
=> Forward the CI env to bazel actions when running coverage CI targets.

README.md
The way to use the "output transformation command" is not very intuitive. 
I believe this example will facilitate the understanding of its use for future interested developers.
Signed-off-by: Lucas Martinez <lucasoctaviom@gmail.com>
=> Add example for output format transformation

bazel/repositories.bzl, source/server/README.md
Changes required:
- Documentation update for nighthawk test server.
=> Update envoy to bc63067

bazel/repositories.bzl, ci/run_envoy_docker.sh
=> Update Envoy to c4fe2ac (Jul 06, 2022)

README.md
=> Add virtualenv and requirements.txt tips

benchmarks/envoy_proxy.py, test/integration/integration_test_fixtures.py
=> Fix spelling.

bazel/repositories.bzl
=> Update envoy to 6b83db4.

benchmarks/envoy_proxy.py, test/integration/BUILD, test/integration/nighthawk_test_server.py, test/integration/unit_tests/BUILD, test/integration/unit_tests/injected_file.txt, test/integration/unit_tests/test_utility.py, test/integration/utility.py
=> Move substitute_yaml_values to test utilities and add unit test.

api/configuration/BUILD, api/configuration/endpoints_config_manager.proto, benchmarks/BUILD, benchmarks/configurations/dynamic_resources_eds.yaml, benchmarks/dynamic_config_envoy_proxy.py, benchmarks/dynamic_test/test_cds_churn_with_traffic.py, benchmarks/dynamic_test/test_eds_churn_with_traffic.py, benchmarks/envoy_proxy.py, dynamic_config/BUILD, dynamic_config/dynamic_config_manager.py, dynamic_config/dynamic_config_manager_test.py, dynamic_config/dynamic_config_server.py, test/dynamic_config/BUILD, test/dynamic_config/dynamic_config_manager_test.py, test/integration/integration_test_fixtures.py
=> Enhancements to support EDS churn test. Add single cluster EDS churn test.

source/client/stream_decoder.cc
=> Fix log statement to log header map and not the pointer

benchmarks/BUILD, benchmarks/dynamic_test/test_cds_churn_with_traffic.py, benchmarks/dynamic_test/test_eds_churn_with_traffic.py
=> Make benchmark duration env configurable for dynamic tests.

benchmarks/dynamic_test/test_cds_churn_with_traffic.py, benchmarks/dynamic_test/test_eds_churn_with_traffic.py
=> Ignore failures which are expected due to config churn.

bazel/repositories.bzl, benchmarks/dynamic_config_envoy_proxy.py, benchmarks/envoy_proxy.py, test/integration/integration_test_fixtures.py
- update [bazel/repositories.bzl](https://github.com/envoyproxy/nighthawk/blob/main/bazel/repositories.bzl)
- fix python format
- all other files synced
Signed-off-by: qqustc <qqin@google.com>
=> Update Envoy to d7df348

OWNERS.md
=> Update the list of active maintainers.

.bazelrc, bazel/repositories.bzl, requirements.txt
- sync bazel/repositories.bzl, .bazelrc
- update requirements.txt
Signed-off-by: qqustc <qqin@google.com>
=> update Envoy to e623c73 (2023-02-13)

.azure-pipelines/bazel.yml
This should fix current errors on postsubmit
=> ci: Enable docker in build container

.bazelrc, bazel/repositories.bzl, tools/code_format/config.yaml
- Sync files
- no code changes
=> Update Envoy to 43d6954 (2023/05/15)

source/client/process_impl.cc
The deferred initialisation of stats (https://github.com/envoyproxy/envoy/pull/23921) requires server instances to always implement `statsConfig()`. This PR adds a dummy implementation for `NighthawkServerInstance`.
Tested with `Bazel test //test/...`
=> Implement NighthawkServerInstance::statsConfig

.bazelrc, bazel/repositories.bzl
- sync .bazelrc
- no code change
=> update Envoy to bd0dc56 2023/08/07

bazel/repositories.bzl, tools/code_format/config.yaml
- Trial run of https://github.com/envoyproxy/nighthawk/pull/1020
- Performed these steps: https://gist.github.com/eric846/b20ea334875322e7adefccad0f77dd3b
=> Update Envoy to 154219f (Sep 11, 2023)

.bazelrc, bazel/repositories.bzl, ci/run_envoy_docker.sh, test/integration/nighthawk_test_server.py
- sync .bazelrc etc
- update a warning msg due to https://github.com/envoyproxy/envoy/pull/28202
Replaces #1027
=> Update Envoy to e4992b9 (Oct 09, 2023)

bazel/repositories.bzl, ci/run_envoy_docker.sh, tools/code_format/config.yaml
- sync files
- no code changes
=> Update Envoy to 58588bd (Nov 06, 2023)

.github/dependabot.yml, .github/workflows/scorecard.yml
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> Setup OSSF Scorecard workflow

.github/dependabot.yml, README.md, benchmarks/docker/Dockerfile-benchmark, ci/docker/Dockerfile-nighthawk, ci/docker/Dockerfile-nighthawk-benchmark
Help improve ossf score
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> ossf: pin docker versions

README.md
This pull request adds a small amount of additional, helpful information that I feel first-time users like myself might find useful as they try to use this tool
=> Add some additional documentation to the README

bazel/repositories.bzl
=> Update Envoy to dcba183 2024/01/22

bazel/repositories.bzl
=> Update Envoy to 7c41010 (Feb 20, 2024)

bazel/repositories.bzl, source/client/process_impl.cc, test/client_worker_test.cc, test/flush_worker_test.cc, test/worker_test.cc
- Update ENVOY_COMMIT to 42904c5.
- Update the way to initialize Envoy Runtime Loader by LoaderImpl::create in source/client/process_impl.cc.
- Update the Runtime Loader initialization in tests.
=> Update Envoy to  42904c5 (May 03, 2024)

bazel/repositories.bzl, tools/code_format/config.yaml
=> Update Envoy to 3ab83ee (Jul 25, 2024)

.bazelrc, bazel/repositories.bzl, ci/run_envoy_docker.sh, tools/base/requirements.in, tools/base/requirements.txt
- `requirements.txt` regenerated
- Incoming changes to `.bazelrc` and `ci/run_envoy_docker.sh`
- https://github.com/envoyproxy/envoy/commit/883c8f758ca4fa620c0e17c74dd14ea6aa4c7264#diff-544556920c45b42cbfe40159b082ce8af6bd929e492d076769226265f215832f
- https://github.com/envoyproxy/envoy/commit/0d39eef892c859483773c4c9a601fd2d0cba4f57#diff-544556920c45b42cbfe40159b082ce8af6bd929e492d076769226265f215832f
=> Update Envoy to 39851cd (Sep 27, 2024)

bazel/repositories.bzl
Update Envoy to the as latest version as possible.
=> update Envoy to commit b253ff8

.bazelrc, bazel/repositories.bzl, ci/do_ci.sh
- update envoy commit and sha.
- update .bazelrc.
- update ci/do_ci.sh to use gcc when setup_gcc_toolchain.
=> update envoy to 8f16edb

bazel/repositories.bzl, source/common/statistic_impl.cc, source/common/statistic_impl.h
Some source file locations changed, hence this comes with changes to reflect that.
=> Update HDR_HISTOGRAM_C_VERSION 0.11.2 -> 0.11.8

bazel/repositories.bzl
just update the commit number. No further updates needed.
=> Envoy update to commit b6ac394
