README.md
include/nighthawk/client/BUILD
include/nighthawk/client/benchmark_client.h
include/nighthawk/client/options.h
include/nighthawk/client/prefetchable_pool.h
source/client/benchmark_client_impl.cc
source/client/benchmark_client_impl.h
source/client/client_worker_impl.cc
source/client/factories_impl.cc
source/client/options.proto
source/client/options_impl.cc
source/client/options_impl.h
test/benchmark_http_client_test.cc
test/factories_test.cc
test/mocks.h
test/options_test.cc
test/test_data/output_formatter.json.gold
test/test_data/output_formatter.yaml.gold

Enabling connection prefetching will cause the client to open the requested amount of connections to the benchmark target, before performing the actual benchmark. The prefetching is only performed intially.

 Connection prefetching feature

---

BUILD
api/server/BUILD
api/server/response_options.proto
ci/do_ci.sh
source/server/BUILD
source/server/README.md
source/server/http_test_server_filter.cc
source/server/http_test_server_filter.h
source/server/http_test_server_filter_config.cc
test/server/BUILD
test/server/http_test_server_filter_integration_test.cc

Introduces a test origin for Nighthawk, based on Envoy.
Current functionality is simple: the request headers can be used to indicate how many bytes the response body should have, and response headers can be added/appended. The response consist of repeating the character `a`.
Deprecates envoyproxy/envoy-perf#70

Simple test origin

---

.clang-tidy
test/client_worker_test.cc
test/mocks.cc
test/mocks.h
test/sequencer_test.cc

Fixes several issues. Also, now that `clang-tidy` runs fully clean, let's turn warnings to errors.
My hopes are up that this deflakes `clang-tidy` in CI.

Get us a fully clean clang-tidy run

---

README.md
api/client/BUILD
api/client/options.proto
api/client/output.proto
api/server/response_options.proto
include/nighthawk/client/benchmark_client.h
include/nighthawk/client/options.h
include/nighthawk/common/statistic.h
source/client/BUILD
source/client/benchmark_client_impl.cc
source/client/benchmark_client_impl.h
source/client/client.cc
source/client/factories_impl.cc
source/client/options_impl.cc
source/client/options_impl.h
source/client/stream_decoder.cc
source/client/stream_decoder.h
source/common/BUILD
test/benchmark_http_client_test.cc
test/factories_test.cc
test/mocks.h
test/options_test.cc
test/output_formatter_test.cc
test/stream_decoder_test.cc

Adds static request parameterization options to NH:
- Request method (`--request-method FOO`)
- Request headers (`--request-header foo:bar`)
- Request entity body size is adjustable (`--request-body-size 123`)
This fixes https://github.com/envoyproxy/nighthawk/issues/20
Moves some proto's into to where they belong: `/api/client` (tech-debt).
Fixes https://github.com/envoyproxy/nighthawk/issues/56

Static request parameterization

---

.bazelrc
.circleci/config.yml
.clang-tidy
WORKSPACE
ci/do_ci.sh
ci/run_clang_tidy.sh
source/client/factories_impl.cc
source/common/statistic_impl.cc
test/benchmark_http_client_test.cc
test/client_test.cc
test/sequencer_test.cc
test/statistic_test.cc

- Update Envoy submodule to the latest
- Use clang-8 for everything, including clang-tidy-8
- Upgrade the CI image
- Tidies up a few things, and drops the linker override hack (obsolete).
This ought to fail some CI tests, the next commit will fix that.
Fixes https://github.com/envoyproxy/nighthawk/issues/62

Update CI image & Envoy, move to clang-tidy-8

---

.bazelrc
.gitmodules
WORKSPACE

This makes the build/VCS situation more consistent. It was necessary
to fork .bazelrc.
It is still possible to use a local Envoy directory via the CLI
--override_repository envoy=<path to your Envoy tree> Bazel build/test
flag, e.g.
bazel test -c fastbuild --override_repository \
envoy=/some/local/path/envoy //test:nighthawk_test
Signed-off-by: Harvey Tuch <htuch@google.com>

build: switch Envoy to an http_archive.

---

.gitignore
README.md
ci/do_ci.sh
ci/run_clang_tidy.sh
source/client/client.cc
test/client_worker_test.cc
test/factories_test.cc
test/stream_decoder_test.cc
test/worker_test.cc

- Don't reference real-world time sources from production code
- Undo accidental add of Envoy submodule in d67558a
- Add `envoy/` to `.gitignore` to prevent that from happening again.
- Doc: Use `-c dbg` when testing
- CI: Reduce parallelism for `clang-tidy`

A couple of fixes

---

bazel/repositories.bzl

Fixes #67.
Signed-off-by: Harvey Tuch <htuch@google.com>

build: fix zlib dependency for hdr histogram.

---

ci/do_ci.sh

This change allows `do_ci.sh` to detect when it is being run in a Docker container,
and conditionally executes setup code specific to that. This is useful for when one
wants to run `do_ci.sh` directly on a system.

do-ci.sh: make docker-specific setup conditional

---

source/client/process_impl.cc
test/process_test.cc

We should lowercase the input to `spdlog::level::from_str`.
Fix that, and add tests to ensure this stays put.
Fixes https://github.com/envoyproxy/nighthawk/issues/108

Fix log level argument parsing

---

integration/test_integration_basics.py
source/client/benchmark_client_impl.cc
source/client/benchmark_client_impl.h
source/client/client_worker_impl.cc
source/client/client_worker_impl.h
source/client/process_impl.cc
source/client/process_impl.h
test/benchmark_http_client_test.cc
test/client_worker_test.cc

As promised in https://github.com/envoyproxy/nighthawk/pull/105
This restores functionality of the connection prefetching feature

Add back the connection prefetching feature

---

integration/integration_test_fixtures.py
integration/test_integration_basics.py
test/process_test.cc

The c++ test started failing when landing on master, because
it conflicts with the new test methology which uses sharding.
(The stderr capturing we used breaks when running in sharded mode)
Move the test to a python-based integration-test equivalent.
Also, reduce log noise in the tests.

Fix the test we have for respecting log verbosity

---

include/nighthawk/common/platform_util.h
source/client/BUILD
source/client/client.cc
source/client/process_impl.cc
source/client/process_impl.h
source/client/service_impl.cc
source/common/platform_util_impl.h
test/mocks.h
test/platform_util_test.cc
test/process_test.cc

Remove `PlatformUtil::determineCpuCoresWithAffinity()` in favor
of `Envoy::OptionsImplPlatform::getCpuCount()`
Fixes https://github.com/envoyproxy/nighthawk/issues/120

Use Envoy's OptionsImplPlatform::getCpuCount()

---

source/client/options_impl.cc

In https://github.com/envoyproxy/nighthawk/pull/123 some doc changes where proposed and merged.
As promised, reflect these in the options implementation as well.

Fix typo's in options_impl.cc

---

test/BUILD
test/integration/BUILD
test/python_test.cc

Get coverage test runs to consider the code hit by our python-based testing.
Fixes https://github.com/envoyproxy/nighthawk/issues/140

Coverage: C++ test wrapper for the python tests

---

source/client/options_impl.cc
source/client/process_impl.cc
source/client/service_impl.cc
source/server/http_test_server_filter.cc

Currently, `bazel build //:nighthawk` fails with the error below. The changes in this commit allow bazel build to pass by catching all exceptions as const references. This also follows standard practices for C++.
```
error: catching polymorphic type 'class Nighthawk::Client::MalformedArgvException' by value [-Werror=catch-value=]
```
Signed-off-by: Teju Nareddy <nareddyt@google.com>

exceptions: Catch all exceptions by const reference

---

source/client/stream_decoder.cc
test/benchmark_http_client_test.cc
test/stream_decoder_test.cc

Stream decoders we create should be aware of any stream reset callbacks on the
associated encoder.
This change resolves a stall when the target server being tested
terminates mid-execution.
This was discovered while testing if the termination predicates
would timely trigger workers to exit.
Split out from https://github.com/envoyproxy/nighthawk/pull/167

Wire up encoder callbacks

---

.gitignore

Remove accidentally committed file & add it to .gitignore.
Split out from https://github.com/envoyproxy/nighthawk/pull/167

Remove default.profraw

---

test/integration/test_integration_basics.py

Adds a small integration test for ensuring `--request-body-size`
does what it says on the tin
(split out from https://github.com/envoyproxy/nighthawk/pull/167, which didn't end up needing it.
this also gets us coverage for a line or two)

Test request body transmission

---

PROFILING.md

Mention that one should set some `--test_env=` options to avoid noise
from the heap profiler in reports.

PROFILING.md: doc update - disable heap profiling

---

source/client/options_impl.cc
test/client/utility.cc
test/client/utility.h
test/options_test.cc

(This is a redo of pull#194).
This is needed to send server configuration through the
`x-nighthawk-test-server-config` request header. Besides, ':' and
whitespace are allowed in header values.
A header argument must contain a ':' that delimits the name and value.
Tested using `bazel test test:options_test` and invoking
`nighthawk_client` with argument `--request-header
'x-nighthawk-test-server-config: { "response_body_size": 1 }'`.
Signed-off-by: Jay Ramamurthi <jramamurthi@google.com>

Change header arg parsing to support ':' in values.

---

source/common/sequencer_impl.cc
test/sequencer_test.cc

When it is time to start releasing requests, don't initiate
work via the deferred path (e.g. timers, sleep), but enter the tight
loop right away. 
Filed https://github.com/envoyproxy/nighthawk/issues/203 for tracking a good follow up to this.

Sequencer:  improve initial loop resolution

---

test/integration/integration_test_fixtures.py
test/integration/test_connection_management.py
test/integration/test_integration_basics.py
test/integration/test_integration_zipkin.py

- Should help with stable CI runs
- Speeds up some tests by relying on termination predicates to bound the number
of requests instead of relying on duration + rps.
- Fixes a bug in runNighthawkClient() for when expect_failure is set.
In some places, we now explicitly pass `--connections 1`.
This is needed because earlier, we changed the default from that
from 1 to 100, which added some entropy.
Fixes https://github.com/envoyproxy/nighthawk/issues/210

Integration test stabilization & speedup

---

source/client/stream_decoder.h
test/integration/integration_test_fixtures.py
test/integration/test_integration_basics.py

Following a report that came in via a backchannel,  remove
NOT_IMPLEMENTED_GCOVR_EXCL_LINE and add tests that will hit those.
Suspiciously, server side expectations fail with larger request body
sizes. That is pending investigation, I will file a separate issue for
that. Meantime, the test lines for that are commented out.

StreamDecoder: amend onXXXWriteBufferHighWatermark

---

include/nighthawk/client/BUILD
include/nighthawk/common/BUILD
include/nighthawk/common/request.h
include/nighthawk/common/request_source.h
source/client/BUILD
source/client/benchmark_client_impl.cc
source/client/benchmark_client_impl.h
source/client/factories_impl.cc
source/common/BUILD
source/common/request_impl.h
source/common/request_source_impl.cc
source/common/request_source_impl.h
test/BUILD
test/benchmark_http_client_test.cc
test/request_generator_test.cc

This adds infrastructure in preparation of
sending dynamic requests / validating request-level expectations.
No functional changes.
Prelude to #137, where add a feature which
streams  to-be replayed requests from a gRPC remote service method.

Introduce Request / prepare dynamic request generation

---

.circleci/config.yml
ci/do_ci.sh
source/client/service_main.cc

- Don't  ignore return value of `write()`
- Add opt build to CI to avoid regression
- While at it, I noticed CI didn't target the output transform utility.
Amend that, and just target the `nighthawk` target, which will build
all binaries.
Fixes https://github.com/envoyproxy/nighthawk/issues/233

Fix opt build of nighthawk_service

---

source/exe/client_main_entry.cc
test/integration/test_integration_basics.py

The CLI doesn't output a helpful error message when an argument
is supplied that passes proto validation but is found to be no good
nonetheless later on.
Fixes https://github.com/envoyproxy/nighthawk/issues/236

Address CLI incidental argument error suppression

---

CONTRIBUTING.md
MAINTAINERS.md
OWNERS.md

- A pre-merge checklist
- Documents what goes into an update to the Envoy dependency
Fixes https://github.com/envoyproxy/nighthawk/issues/230

First stab at MAINTAINERS.md & OWNERS.md & CONTRIBUTING.md

---

MAINTAINERS.md

Update MAINTAINERS.md: mention pre-merge commit message cleanup

---

README.md
api/client/options.proto
api/client/transform/fortio.proto
include/nighthawk/client/options.h
source/client/options_impl.cc
source/client/options_impl.h
source/client/output_formatter_impl.cc
test/mocks.h
test/options_test.cc
test/test_data/output_formatter.json.gold
test/test_data/output_formatter.medium.proto.gold
test/test_data/output_formatter.yaml.gold

Adds a new `--label` option. Allows tagging executions with multiple
labels. These labels will be persisted in our structured output formats.

Labels option

---

ci/do_ci.sh

Adds missing commands into the help message produced by do_ci.sh.

add missing do_ci.sh commands into the help message

---

test/rate_limiter_test.cc

Bypassed the random number generator in the test until we have a better solution (#263). (Now the fake distribution returns 500000 every time.) This test is for code that isn't wired in yet, so there is zero impact on users.
We need to update to the latest version of Nighthawk for a project that depends on new features, and this test is the only thing blocking the import.

Temporary fix for TimingVerificationTest determinism

---

test/rate_limiter_test.cc

As per discussion on th issue, this is great as-is.
So this comment should be backed out.
Sorry about the noise!
Closes #263

Remove TODO(#263) code comment

---

bazel/repositories.bzl

https://github.com/HdrHistogram/HdrHistogram_c/releases/tag/0.9.12

HdrHistogram: 0.9.11 -> 0.9.12

---

README.md
source/client/options_impl.cc

CLI: Avoid double angle brackets in docs

---

source/common/rate_limiter_impl.cc
source/common/rate_limiter_impl.h
test/rate_limiter_test.cc

As per discussion [1], this is intended to be used as a replacement
for the way we offset worker request release timings today.
[1] https://github.com/envoyproxy/nighthawk/pull/219#discussion_r366537002

rate-limiting: Add ScheduledStartingRateLimiter

---

api/client/options.proto

Applies the documentation that is available in the README from TCLAP into the proto file directly, for consumption there by gRPC consumers.  Adds in some notes for fields that are not relevant to the gRPC service.

Update CommandLineOptions proto documentation for grpc users

---

README.md
api/client/options.proto
docs/root/version_history.md
include/nighthawk/client/options.h
source/client/client_worker_impl.cc
source/client/client_worker_impl.h
source/client/options_impl.cc
source/client/options_impl.h
source/client/process_impl.cc
test/client_test.cc
test/client_worker_test.cc
test/integration/test_connection_management.py
test/integration/test_integration_basics.py
test/mocks.h
test/options_test.cc

The current single request we issue for the simple warmup pollutes
some of the counters we emit in our output.
Looking forward, when landing generic phases, we might want to
default to opting out.
This new flag could then serve as an opt-in afterwards, for those
who want to preserve old behavior.

Simple warmup: default to opting out

---

source/client/process_impl.cc
source/common/uri_impl.cc

Today, we use TCP for resolving DNS. This makes us use UDP
instead. I think the choice here was never actively discussed,
and possibly the current default crept in via an Envoy dep
update.
Fixes https://github.com/envoyproxy/nighthawk/issues/300

Dns resolution: use UDP instead of TCP

---

api/client/transform/fortio.proto
source/client/output_formatter_impl.cc
source/client/output_formatter_impl.h
test/output_formatter_test.cc
test/test_data/output_formatter.medium.fortio.gold

This adds two new fields to the fortio output:
```proto
// Bytes sent should reflect the bytes sent after protocol serialization, compression, and
// encryption are applied (i.e., the size of the buffers passed to the send() system call or its
// equivalent).
uint64 BytesSent = 18;
// Bytes received should reflect the bytes read before decryption, de-compression, and protocol
// de-serialization are applied (i.e., the size of bytes read from the recv() system call or its
// equivalent).
uint64 BytesReceived = 19;
```

Fortio output: add bytes sent / received

---

include/nighthawk/client/options.h
test/BUILD
test/client_worker_test.cc
test/factories_test.cc
test/mocks.cc
test/mocks.h
test/mocks/client/BUILD
test/mocks/client/mock_options.cc
test/mocks/client/mock_options.h
test/output_formatter_test.cc

Part of an effort to attempt to reduce memory usage during
the build, to address ASAN flakes in CI.

Move MockOptions into its own compilation unit.

---

include/nighthawk/common/BUILD
test/BUILD
test/benchmark_http_client_test.cc
test/client_worker_test.cc
test/factories_test.cc
test/mocks.cc
test/mocks.h
test/mocks/client/BUILD
test/mocks/client/mock_benchmark_client.cc
test/mocks/client/mock_benchmark_client.h
test/mocks/client/mock_options.cc
test/mocks/common/BUILD
test/mocks/common/mock_rate_limiter.cc
test/mocks/common/mock_rate_limiter.h
test/mocks/common/mock_sequencer.cc
test/mocks/common/mock_sequencer.h
test/mocks/common/mock_termination_predicate.cc
test/mocks/common/mock_termination_predicate.h
test/rate_limiter_test.cc
test/sequencer_test.cc

Part of an effort to attempt to reduce memory usage during
the build, to address ASAN flakes in CI.
- This is a mechanical change, no functional changes
- Moves the mocks for:
- BenchmarkClient
- RateLimiter
- TerminationPredicate
- Sequencer
- Contains some additional cleanup.

Move a couple of mocks into their own compilation units

---

test/BUILD
test/client_worker_test.cc
test/mocks.cc
test/mocks.h
test/mocks/common/BUILD
test/mocks/common/mock_platform_util.cc
test/mocks/common/mock_platform_util.h
test/mocks/common/mock_request_source.cc
test/mocks/common/mock_request_source.h
test/sequencer_test.cc

Part of an effort to attempt to reduce memory usage during
the build, to address ASAN flakes in CI.
- This is a mechanical change, no functional changes.
- Does have some additional cleanup.

Move MockPlatformUtil and MockRequestSource

---

include/nighthawk/client/factories.h
source/client/BUILD
source/client/factories_impl.cc
source/client/factories_impl.h
source/client/process_impl.cc
source/client/process_impl.h
test/factories_test.cc

Just noticed some code that no longer is actually used.
Context:
StoreFactory became obsolete when it became apparent that
the isolated stats store implementation didn't have enough
production mileage to be a suitable candidate. We switched
to use the thread local backing store.
Today NH is basically hard-coupled to that store, as it builds
on top of some of its shared semantics, so this abstraction
probably will not be useful in the foreseeable future.

Dead code: eliminate StoreFactory

---

bazel/repositories.bzl
source/common/uri_impl.cc

One change on the NH side: Envoy's Dns resolution api changed.
Updates Envoy to 3a2512d923e2eee1fce9f4f6a23cf93f2e7ed93f

Update Envoy dep

---

ci/do_ci.sh

- Perform the build in incremental steps, to reduce memory footprint of the build.
- Additionally, separate test and build, to ensure they won't run concurrently. This helps stabilize the python integration test.
These two things combined seem to help stabilize ASAN in CI. I could confirm a couple of
consecutive succeeding CI runs:
https://app.circleci.com/pipelines/github/envoyproxy/nighthawk?branch=pull%2F315
Associated issue: https://github.com/envoyproxy/nighthawk/issues/272
Leaving that open for now, let's close it later if we're confident the problem is resolved.

CI/ASAN: Break ASAN build in multiple steps to reduce memory usage

---

bazel/repositories.bzl
source/client/BUILD
source/client/process_impl.cc
source/client/process_impl.h
test/output_formatter_test.cc
test/utility_test.cc

Update to the latest + fixes to unbreak the build

Update Envoy to 3a2512d923e2eee1fce9f4f6a23cf93f2e7ed93f

---

.bazelrc
bazel/repositories.bzl
source/client/process_impl.cc

Update Envoy to c34b82f261be45f60a4df8e40937f4066d20797b

---

test/BUILD

Cleaning up an unused loader `envoy_cc_mock`
Risk: Low
Signed-off-by: Adi Suissa-Peleg <adip@google.com>

Removing unused loader envoy_cc_mock

---

ci/do_ci.sh

Another stab at https://github.com/envoyproxy/nighthawk/issues/272
Since the last Envoy update the ASAN build runs out of memory more often then not.
I noticed that the earlier attempt at reducing `NUM_CPUS`/`--jobs` didn't yield expected
results in CI, as bazel would still be running 8 jobs in parallel.
Upon investigation, I noticed that my earlier attempt had issues:
- it set the wrong variable
- upon fixing that, the script would end up handing two `--jobs=x` arguments to bazel
The approach here sets `NUM_CPUS` early on in the script, and doesn't attempt to mess
with the build flags later on.
Hopefully fixes https://github.com/envoyproxy/nighthawk/issues/272

CircleCI: reduce ASAN parallelism

---

.bazelrc
bazel/repositories.bzl
source/client/process_impl.cc
source/common/worker_impl.cc
test/benchmark_http_client_test.cc
test/server/http_test_server_filter_integration_test.cc
test/stream_decoder_test.cc
test/utility_test.cc

Update Envoy to 582ab4a353ac2c19f4326115b471cebeabe7ae8a

---

source/client/process_impl.cc
source/client/process_impl.h
test/BUILD
test/client_worker_test.cc
test/integration/integration_test.py
test/integration/test_integration_basics.py

Related to https://github.com/envoyproxy/nighthawk/issues/317
Log any exceptions and rethrow. This is to assist with
diagnosis once it happens again in the CI env.

Log exception in ProcessImpl::run()

---

test/server/http_test_server_filter_integration_test.cc

We don't reliably cover all flows in `HttpTestServerDecoderFilter::sendReply()`.
Add a c++ unit test to address that and stop this particular source of CI coverage
flakes.
Fixes https://github.com/envoyproxy/nighthawk/issues/296

Coverage: HttpTestServerDecoderFilter::sendReply()

---

include/nighthawk/client/factories.h
include/nighthawk/client/output_collector.h
include/nighthawk/client/output_formatter.h
include/nighthawk/common/request.h

Fixes https://github.com/envoyproxy/nighthawk/issues/268

Supplement doc comments in interface headers.

---

api/server/response_options.proto
source/server/README.md
source/server/http_test_server_filter.cc
source/server/http_test_server_filter.h
test/server/http_test_server_filter_integration_test.cc

If `echo_request_headers` option is set to `true`, then request headers dump is appended to the response body.

Add echo_request_headers to the test server filter ResponseOptions.

---

test/integration/nighthawk_grpc_service.py
test/integration/nighthawk_test_server.py
test/integration/test_connection_management.py
test/integration/test_grpc_service.py
test/integration/test_integration_basics.py
test/integration/test_remote_execution.py

This PR has changes to deflake integration tests for sanitizer runs.
- Allow servers more time to start up
- Slow down some tests to make them less sensitive to timing issues 
- It is possible for some counter values to slightly exceed a configured termination threshold
for them in edge cases. Update expectations to match that. 
Fixes #332

integration-tests: tweaks to stabilize sanitizer runs

---

README.md
api/client/options.proto
include/nighthawk/client/options.h
source/client/factories_impl.cc
source/client/options_impl.cc
source/client/options_impl.h
source/client/process_impl.cc
source/common/termination_predicate_impl.cc
source/common/termination_predicate_impl.h
test/mocks/client/mock_options.h
test/options_test.cc
test/run_nighthawk_bazel_coverage.sh

Adds `--no-duration`, which will be treated as a request to infinitely
continue load generation.  Other default predicates will still exist, so\
execution may still stop when connection failures or error response codes
are observed.
This leaves some small tech debt:
- We need test coverage, but that's much easier to add once
#280 or #344 goes in
Fixes #333

Add "no-duration" to facilitate infinite load generation

---

test/termination_predicate_test.cc

TerminationPredicateTest: explicitly order std::move/get reference

---

test/benchmark_http_client_test.cc

Fix benchmark_http_client_test.cc which has a bug in function testBasicFunctionality().
For example, if we have a test fixture with testBasicFunctionality(max_pending=0,connection_limit=15,amount_of_request=10),
then EXPECT_FALSE(client_->tryStartRequest(f)) and
EXPECT_EQ(max_pending == 0 ? 1 : max_pending, inflight_response_count) will fail.
For test fixture with
testBasicFunctionality(max_pending=2,connection_limit=3,amount_of_request=10),
EXPECT_EQ(max_pending == 0 ? 1 : max_pending, inflight_response_count) will fail.
Added 2 test cases to verify the expected behavior fixed by this change.
Tested:
Unit test.

Fix benchmark_http_client_test.cc and add test cases.

---

bazel/repositories.bzl
source/client/benchmark_client_impl.cc
source/client/process_impl.cc

Notable changes:
- Fixes our Http1PoolImpl to work with the updated Envoy
code.
- Tweaks the cluster setup: we specify at least an empty
http2_protocol_options proto config. Without doing this
passing --h2 to the nighthawk client would fail as caught
by tests.
- Moves away from using hidden_envoy_deprecated_hosts.
Side effect of looking into the bevavioral change listed
above. This resolves #377. (strictly not needed for this
update).

Update Envoy to 5c553261d14730af5a2c290c4b3687ae667a65db

---

bazel/repositories.bzl

This brings in some enhancements that I think would be good to have.
For those who like to get a higher resolution view of what changed in the HdrHistogram_c dep
update proposed here, see:
https://github.com/HdrHistogram/HdrHistogram_c/compare/0.9.13...0.11.0

Update HdrHistogram_c to 0.11.0

---

requirements.txt

Add missing dependencies to run tools/gen_compilation_database.py successfully. This command will create the files needed for CLang intellisense to work.

Add missing dependencies to run tools/gen_compilation_database.py 

---

.bazelrc
bazel/repositories.bzl
ci/do_ci.sh
source/client/BUILD
source/client/benchmark_client_impl.h
source/client/process_impl.h
source/client/stream_decoder.h
source/server/README.md
test/BUILD
test/benchmark_http_client_test.cc
test/client_worker_test.cc
test/stream_decoder_test.cc
test/worker_test.cc

Update Envoy + run gcc-built tests in CI because now we can.
Fixes #382
-----
Prerequisite: 

Update Envoy to 7abb0e0bbed4f6b6304403b93762614ad385f80d

---

ci/do_ci.sh

Compared to clang, gcc uses more memory. Lower parallelism to
avoid the build running out of memory.

CI: lower test_gcc parallellism.

---

include/nighthawk/common/factories.h
source/client/BUILD
source/client/flush_worker_impl.cc
source/client/flush_worker_impl.h
source/client/process_impl.cc
source/client/process_impl.h
source/common/statistic_impl.cc
source/common/statistic_impl.h
test/BUILD
test/flush_worker_test.cc
test/process_test.cc
test/statistic_test.cc

Add a flush worker to periodically flush stats to sinks.
Add the functionality to configure sinks in process_impl.cc
Start the flush worker in process_impl.cc when there is stats sink configured.
Change the SinkableStatistic's tagExtractedName() to return `worker_id + "." + Nighthawk::Statistic::id()` which can be used in customized sinks.
Linked Issues: #344
Signed-off-by: Qin Qin <qqin@google.com>

Add the functionality to flush stats to sinks periodically in NH

---

ci/do_ci.sh
requirements.txt

Pin python versions to recent versions. 
CI broke on pytest-xdist releasing `2.0.0` which got pulled in.
Signed-off-by: Otto van der Schaaf oschaaf@we-amp.com

Python requirements.txt - pin to (recent) versions 

---

.bazelrc
.circleci/config.yml
bazel/repositories.bzl
ci/do_ci.sh

Updated Envoy, plus a tweak to deflake the gcc test in CI.

Update Envoy to 933e67a9ecac814839f514fb5c31c78f3d33e5fe

---

source/client/benchmark_client_impl.cc
source/client/benchmark_client_impl.h
source/client/process_impl.cc
source/client/process_impl.h
source/common/sequencer_impl.h

Envoy's statistics macros seem to no longer need this,
so we can do without "using namespace Envoy".
Also fix things that have crept in and relied on this.

Eliminate instances of "using namespace Envoy"

---

.bazelrc
bazel/repositories.bzl
extensions_build_config.bzl

Allows us to use ENVOY_LOG_MISC without needing to specify
"using namespace Envoy" via
https://github.com/envoyproxy/envoy/commit/963d169a9f87d7b60fa02894639e10d4972be3c9

Update Envoy to d3abda8a32cb11e9b251deb5ffd2601096c80b57

---

.circleci/config.yml

Whoops, I think I found why the integration test coverage task in not
showing in CircleCI. Next to defining it, it should be separately enabled too.

Fix (enable) integration test coverage in CI

---

ci/do_ci.sh
source/common/uri_impl.cc
test/client_test.cc
test/integration/test_integration_basics.py
test/utility_test.cc

- Avoid std::stoi exception during uri parsing
- Add unit tests for client.cc to improve coverage

Fix uri parsing bug & add some unit test coverage for client.cc

---

bazel/repositories.bzl

This gets us a bunch of sparse logging macros:
ENVOY_LOG_FIRST_N
ENVOY_LOG_ONCE
ENVOY_LOG_EVERY_NTH
ENVOY_LOG_EVERY_POW_2

Update Envoy to f1c0031819ddc7b8a9f6352ad6722f4abf8ab664

---

source/client/benchmark_client_impl.cc
source/client/stream_decoder.cc
source/common/statistic_impl.cc

Throttle log emission in a few potentially high frequency paths.
Fixes #484

Avoid high frequency logging

---

api/client/options.proto
source/client/options_impl.cc
source/client/output_formatter_impl.cc
test/options_test.cc
test/output_formatter_test.cc

Allow 0s as a value to the jitter-uniform option.

---

ci/do_ci.sh

Recently integration test coverage started to occasionally flake just below the configured threshold.
While not passing the coverage integration threshold isn't blocking merge of PRs,  the red cross marking CI failure for a PR isn't encouraging.
Therefore I'm proposing to lower this threshold to avoid further flakes, and make it more valuable as a signal to authors/reviewers to inspect its reports upon failure.

Lower integration test coverage threshold

---

CONTRIBUTING.md
MAINTAINERS.md
OWNERS.md

Also explicitly add in some repo conventions about maintaining and contributing to nighthawk.

Add dubious90 to the list of owners.

---

ci/docker/default-config.yaml
test/integration/configurations/nighthawk_http_origin.yaml

Our own dynamic delay extension owns this now. We no longer
need it in tests.
Split out from #512 

Eliminate configuration references to Envoy's fault filter.

---

test/integration/configurations/nighthawk_http_origin.yaml
test/integration/test_integration_basics.py

Make the end-to-end test for POST handling cover all extensions.
Split out from #512 

Enhance end-to-end test for POST requests with an entity body.

---

ci/do_ci.sh

This is helpful to assist with building Nighthawk's production
ready artifacts via docker build images.
For example:
```bash
DOCKER_IMAGE=envoyproxy/envoy-build-[centos|ubuntu] \
ci/run_envoy_docker.sh ci/do_ci.sh opt_build
```
Related issue: #525

Add opt_build option to ci/do_ci.sh.

---

ci/do_ci.sh

Now that we have a benchmark docker image build, it would be
good to make sure that keeps working in CI.
This also makes it easy to start pushing this image in CI in a
follow-up.

Test benchmark docker image build in CI

---

README.md
api/client/options.proto
source/client/output_formatter_impl.cc
source/client/output_formatter_impl.h
test/BUILD
test/output_formatter_test.cc
test/test_data/output_formatter.medium.fortio-noquirks.gold

Adds a post-processing step to massage the fortio output formatting
to more exactly reproduce Fortio's output, while leaving the
original output formatter intact for backwards compatibility purposes.
Fixes known issues #422 and #514. Experimental until we have
some confirmation that this can be marked as final / all issues have
been resolved.

Add experimental "pedantic" fortio output formatter.

---

source/client/factories_impl.cc
test/output_transform_main_test.cc

I forgot the last step, which is to actually teach the output
formatter factory when to construct the new formatter. Sorry!
- Amends a pre-existing test to avoid regression when adding new
output formats in the future
- Fix the issue, add the new proto enum option to the switch
statement.
Fixes #543

Avoid crash with the experimental fortio pedantic formatter

---

source/server/BUILD
source/server/http_dynamic_delay_filter.cc
source/server/http_dynamic_delay_filter.h
source/server/http_filter_config_base.cc
source/server/http_filter_config_base.h
source/server/http_time_tracking_filter.cc
source/server/http_time_tracking_filter.h

Second step in unifying configuration handling across extensions:
make these two extensions inherit from and use FilterConfigurationBase.
Fix POST handling.
Split out from #512

Switch dynamic delay and time-tracking to use FilterConfigurationBase.

---

source/client/BUILD
source/client/remote_process_impl.cc
source/client/remote_process_impl.h

Drop duplicated code, use the newer code that has better test
coverage plus handling for when multiple results would be received.
This also makes the newer code run with the pre-existing end-to-end testing
for this.
Fixes #496

Implement RemoteProcessImpl in terms of PerformNighthawkBenchmark()

---

test/server/http_dynamic_delay_filter_integration_test.cc
test/server/http_time_tracking_filter_integration_test.cc

Switch tests for these extensions to use the recent shared test
facilities. Eliminate tests we generalize in #533.
Split out from #512
-----

Use shared test facilities for time-tracking and dynamic-delay

---

source/common/rate_limiter_impl.cc
source/common/rate_limiter_impl.h
test/rate_limiter_test.cc

By chance weird behaviour was observed for when specifying large jitter
values. This warranted analysis, and upon investigation the root problem seems
to be that when configuring `--uniform-jitter` to a value that would allow the
adjusted value(s) to overlap with the pacing of the underlying rate limiter,
the new overlapping value could overwrite the old one that was scheduled.
This modifies behaviour and tests to fix and consolidate, by modifying 
`DistributionSamplingRateLimiter` so that it can queue adjusted release
timings instead of storing a single one. This will allow it to accumulate multiple
release timings that are adjusted for jitter. 
This ensures that the pacing of the rate limiter that modifies timings to add jitter
gets properly disconnected from the pacing of the …

Fix jitter behavior for large values.

---

test/integration/test_integration_zipkin.py

Reported via Slack; confirmed to fix a problem when executing
tests on some systems.

Fix import in Zipkin integration tests.

---

include/nighthawk/common/factories.h
source/client/client_worker_impl.cc
source/client/client_worker_impl.h
source/client/factories_impl.cc
source/client/factories_impl.h
source/client/process_impl.cc
source/common/cached_time_source_impl.h
source/common/rate_limiter_impl.cc
source/common/rate_limiter_impl.h
source/common/sequencer_impl.cc
source/common/sequencer_impl.h
source/common/termination_predicate_impl.cc
source/common/termination_predicate_impl.h
test/client_worker_test.cc
test/factories_test.cc
test/mocks/common/mock_sequencer_factory.h
test/mocks/common/mock_termination_predicate_factory.h
test/rate_limiter_test.cc
test/sequencer_test.cc
test/termination_predicate_test.cc

Small refactor that makes the client rely on system time instead of monotonic time
for scheduling the start of worker executions. System clocks can be synchronized
across machines, and this may come in handy when we start facilitating horizontal
scaling. 
Note: `SequencerImpl` gets modified to re-use the execution duration that the `RateLimiter`
it uses already tracks, in favour of its own tracking. This is a small clean up.
Apart from the actual switching from monotonic time to wall clock time, this should be a
mechanical change. 
This change will make things easier if we would like to add an option to schedule the time at
which an execution will start. 
This in turn could be useful when directing clients running on multiple machines to start, as a
means to have them start at …

Use system time for scheduling.

---

.bazelrc
.circleci/config.yml
bazel/repositories.bzl
benchmarks/README.md
ci/do_ci.sh
ci/run_clang_tidy.sh
source/client/process_impl.cc
test/rate_limiter_test.cc

- Update Envoy to 2097fe908f2abb718757dbd4087d793c861d7c5a
- Update HdrHistogram_c to 0.11.2
Adds `--define tcmalloc=gperftools` to the opt build we use to push images,
to (continue to) allow cpu profiling. We need this because of https://github.com/envoyproxy/envoy/commit/4c0d2d2a36996f2ec7d00b519ea90068629a2c55

Update Envoy & HdrHistogram_c

---

.bazelrc
bazel/repositories.bzl
source/client/stream_decoder.cc
source/server/http_filter_config_base.cc
test/request_source/request_source_plugin_test.cc
test/server/http_dynamic_delay_filter_integration_test.cc
test/server/http_filter_base_test.cc
test/server/http_filter_integration_test_base.cc
test/server/http_filter_integration_test_base.h
test/server/http_test_server_filter_integration_test.cc
test/server/http_time_tracking_filter_integration_test.cc
test/stream_decoder_test.cc

Notable changes:
- Handle the new `Envoy::Http::StreamResetReason:: ConnectError` & amend related test
- Handle that `Envoy::Http::HeaderMap::get()` now returns a `Envoy::Http::HeaderMap::GetResult`.
- Squelch Envoy's format check error that scans for urls in `bazel/repositories.bzl`

Update Envoy to f95f5391b0b8683081ec786ea946026594955fc6

---

source/server/http_dynamic_delay_filter.cc
source/server/http_filter_config_base.cc
source/server/http_filter_config_base.h
source/server/http_test_server_filter.cc
source/server/http_time_tracking_filter.cc

Signed-off-by: Kush Trivedi <kushthedude@gmail.com>
fixes #558

chore: enhance naming of bool maybeSendErrorReply

---

ci/do_ci.sh

As discussed yesterday, make clang-tidy ignore failures to stop
the excessive flaking from being a blocker to merge.
This is meant as a temporary stop gap to buy us some time to dig
up the root cause.

CI: make clang-tidy always pass.

---

.bazelrc
.circleci/config.yml
bazel/repositories.bzl
source/client/flush_worker_impl.cc
source/client/stream_decoder.cc
test/benchmark_http_client_test.cc
test/stream_decoder_test.cc

- Handle return value of encodeHeaders() now that there is one.
- MetricSnapshotImpl now needs a TimeSource in its constructor.
- Avoid assert, use valid request header in StreamDecoderTest

Update Envoy to 8e6b176b89240d1b8ce3f3e4a8e276e4a40fcd1e

---

README.md
source/client/options_impl.cc
test/integration/BUILD
test/integration/configurations/nighthawk_http_origin.yaml
test/integration/configurations/nighthawk_https_origin.yaml
test/integration/configurations/nighthawk_track_timings.yaml
test/integration/configurations/sni_origin.yaml
test/integration/test_integration_basics.py
test/options_test.cc

Verified that all integration tests pass after updating Envoy to commit `588d9344b31e6544869547c4bcd359b3b0f1d4cf`, so this PR unblocks #575. Our next steps will be adding a good warning and a compatibility flag for users of Nighthawk. If they do send configs with Envoy API v2, we will break by default, but allow them to continue with the compatibility flag.
Summary of performed changes:
- changing `config` to `typed_config` and listing the correct type.
- migrating from deprecated field `tls_context` to `transport_socket`.
- changing filter names to ones that match extension names in [extensions_build_config.bzl](https://github.com/envoyproxy/nighthawk/blob/master/extensions_build_config.bzl).
- cosmetic changes of enum value from `auto` to `AUTO`.
Also:
- updating README and help …

Migrating configs of integration tests to Envoy API v3.

---

benchmarks/benchmarks.py
test/integration/integration_test.py
test/integration/integration_test_fixtures.py
test/integration/nighthawk_test_server.py
test/integration/test_integration_basics.py

We don't run integration tests in IPv6 mode on CI (See #578). As a result some of the test expectations became invalid.
Also:
- Pytest now displays more logging on test failures including the stderr and stdout of the started nighthawk test server.
- fixing the default IPv6 address, as per `man 3 inet_pton`, the address `::/0` isn't valid, while `::` is.

Fix integration tests when running with IPv6.

---

benchmarks/configurations/envoy_proxy.yaml

Verified the benchmark tests successfully load this configuration after updating Envoy to commit `588d9344b31e6544869547c4bcd359b3b0f1d4cf`.
Summary of performed changes:
- changing `config` to `typed_config` and listing the correct type.
- structural changes to update `clusters` stanza to `v3`.
- changing filter names to ones that match extension names in [extensions_build_config.bzl](https://github.com/envoyproxy/nighthawk/blob/master/extensions_build_config.bzl).
- cosmetic changes of enum values to uppercase form.
Works on #580

Migrating config for benchmark tests to Envoy API v3.

---

README.md
api/client/options.proto
include/nighthawk/client/options.h
source/client/options_impl.cc
source/client/options_impl.h
source/client/process_impl.cc
source/client/process_impl.h
test/integration/BUILD
test/integration/configurations/nighthawk_http_origin_envoy_deprecated_v2_api.yaml
test/integration/configurations/nighthawk_http_origin_v2_api.yaml
test/integration/integration_test_fixtures.py
test/integration/nighthawk_test_server.py
test/integration/test_integration_basics.py
test/mocks/client/mock_options.h
test/options_test.cc
test/process_test.cc

- Adds a new proto/cli option, which allows requesting continued use of the about to be deprecated v2 api's. 
- Adds a new fixture / integration test for the test server, as a sanity check for making sure that when we update Envoy to the 
revision that deprecated v2 things will keep working as expected, while documenting how to set up the runtime configuration.

Add a flag to allow for continued use of the deprecated v2 api

---

bazel/repositories.bzl
source/client/benchmark_client_impl.cc
source/client/benchmark_client_impl.h
source/client/process_impl.cc
source/common/request_source_impl.cc
source/server/README.md

- Fixes to accommodate upstream connection pool changes.
- Fixes to accommodate upstream cluster related changes.

Update Envoy to 588d9344b31e6544869547c4bcd359b3b0f1d4cf

---

source/server/README.md

Verified that an Envoy built after `588d9344b31e6544869547c4bcd359b3b0f1d4cf` can load the configuration from the documents.
Also:
- fixing one typo in the documentation.
- cosmetic changes of enum values to uppercase form.
Works on #580

Updating documentation to use Envoy API v3.

---

api/server/BUILD
api/server/response_options.proto
source/server/BUILD
source/server/configuration.cc
source/server/configuration.h
source/server/http_dynamic_delay_filter_config.cc
source/server/http_test_server_filter_config.cc
source/server/http_time_tracking_filter_config.cc
test/server/BUILD
test/server/configuration_test.cc
test/server/http_dynamic_delay_filter_integration_test.cc
test/server/http_test_server_filter_integration_test.cc
test/server/http_time_tracking_filter_integration_test.cc

Adds a new field `v3_response_headers` alongside the old v2 `response_headers` in `api/server/response_options.proto` and marks the old field as deprecated. The old field retains its functionality for backward compatibility.
Since these are repeated fields, we cannot use a oneof. Instead validation is added to ensure the filters report an error on configuration that has both the v2 and the v3 fields set. `Envoy::EnvoyException` is thrown on validation errors to comply with the `Envoy::Server::Configuration::NamedHttpFilterConfigFactory` interface.
Also:
- sorting imports in `response_options.proto ` alphabetically.
- adding missing anonymous namespace in `http_dynamic_delay_filter_integration_test.cc`.
Works on #580.

Deprecate Envoy API v2 primitives in configuration for our Envoy filters.

---

api/request_source/BUILD
api/request_source/service.proto
source/client/BUILD
source/client/service_impl.cc
source/common/BUILD
source/common/request_stream_grpc_client_impl.cc
test/BUILD
test/request_stream_grpc_client_test.cc

Converting the current field into a `oneof` and marking the `v2` primitive as deprecated. The old field retains its functionality for backward compatibility.
Also:
- sorting imports in `api/request_source/service.proto`.
- migrating our dummy request source to using the `v3` primitive.
- improving error message emitted on test failures in `test/request_stream_grpc_client_test.cc`, the current message just dumps byte representation of the two compared header objects.
Fixes #580.
Signed-off-by: Jakub Sobon mumak@google.com

Deprecate Envoy API v2 primitives in the service proto for Request Source.

---

bazel/repositories.bzl
source/client/benchmark_client_impl.h
test/benchmark_http_client_test.cc
test/client_worker_test.cc
test/factories_test.cc
test/flush_worker_test.cc
test/rate_limiter_test.cc
test/sequencer_test.cc
test/stream_decoder_test.cc
test/worker_test.cc

- The way we can obtain a http connection pool changed. Amend.
- Cleanup by fix_format: strip superfluous .Times(1) in tests.

Update Envoy to 424909395c90d7d68f1afeb3427c26c7c85f2672

---

source/common/utility.cc

The character literal overload is more efficient.

Optimize calls to std::string::find() and friends for a single char.

---

bazel/repositories.bzl
source/client/process_impl.cc
test/mocks/client/mock_benchmark_client.h
test/mocks/common/mock_rate_limiter.h
test/mocks/common/mock_request_source.h
test/mocks/common/mock_sequencer.h
test/mocks/common/mock_termination_predicate.h
test/sequencer_test.cc

- Unbreak changed allocateConnPool() method usage: changes
with respect to ALPN allow negotiation of a protocol,
which is backed in Envoy by a pool which supports >1
protocols. This update leaves a code-level comment plus
a RELEASE_ASSERT when a multi-protocol pool is allocated.
- Avoid MOCK_METHODn as per new check_format objections:
Change our mocks to use MOCK_METHOD instead.

Update Envoy to 867b9e23d2e48350bd1b0d1fbc392a8355f20e35

---

bazel/repositories.bzl
source/client/process_impl.cc
test/common/nighthawk_service_client_test.cc

- Transitively updates the grpc dependency, which eliminated
the grpc_impl namespace. s/grpc_impl::/grpc::/
- Envoy::LocalInfo::LocalInfoImpl constructor now requires passing
a symbol table. Pass that in.
Signed-off-by: Otto van der Schaaf <oschaaf@gmail.com>

Update Envoy to 937f013 (Jan 5th 2021)

---

source/common/signal_handler.cc
source/common/signal_handler.h
test/common/BUILD
test/common/signal_handler_test.cc

Fixes a bug observed while working on horizontal scaling support:
SignalHandler would fire on destruction.
Fix & add tests.
Note: pre-emptive, I don't think this is  an issue in the current
state of master. But some of the CI errors in #600 seemed familiar
and hopefully merging this in there helps.
(Split out from https://github.com/oschaaf/nighthawk/tree/horizontal-scaling)
/cc @eric846

Signal handler: don't fire on destruction

---

.bazelrc
bazel/repositories.bzl
source/client/process_impl.cc
source/client/process_impl.h

Updates the Envoy dependency to revision:
17e815122ff53d0ac6cb2d64cdbf1bfc547bb7e8
Non mechanical change:
- LocalinfoImpl constructor changed

Update Envoy to 17e8151 (Jan 16th 2021)

---

.bazelrc
bazel/repositories.bzl
source/client/benchmark_client_impl.cc

- sync `.bazelrc` from envoy.
- `tryCreateNewConnection` now returns a `ConnPoolImplBase::ConnectionResult` instead of a `bool`.

Update Envoy to 9753819 (Jan 24th 2021).

---

CONTRIBUTING.md
MAINTAINERS.md
PROFILING.md
README.md
RELEASE_PROCEDURE.md
api/adaptive_load/adaptive_load.proto
benchmarks/README.md
ci/docker/docker_push.sh
docs/root/overview.md
docs/root/statistics.md
extensions_build_config.bzl
source/client/options_impl.cc
source/server/README.md

The branch was renamed recently for multiple repositories in the envoyproxy org.

Updating references to branch name master->main.

---

benchmarks/README.md

Changing github repository paths from oschaaf to envoyproxy.

Updating repository paths in README under benchmarks.

---

ci/docker/Dockerfile-nighthawk
ci/docker/Dockerfile-nighthawk-benchmark

I think the root cause is that the alpine-glibc image updates,
and through that dependency requirements can no longer be met.
This PR
- pins the alpine image at the latest version
- changes the dependency versions so they work again
Note: the `>=` for python was changed to `=` as otherwise we'd
write a file to disk mentioning the version, this seemed contra
intent.
There's a complaint [1] emitted during the image build, so we need to
see if everything is OK when CI finishes.
[1] /usr/glibc-compat/sbin/ldconfig: /usr/glibc-compat/lib/ld-linux-x86-64.so.2 is not a symbolic link

CI: Fix broken docker tasks

---

.bazelrc
.circleci/config.yml
bazel/repositories.bzl
source/client/output_formatter_impl.cc
test/output_transform_main_test.cc
test/statistic_test.cc

- synchronizing `.bazelrc` from Envoy repository.
- the API of `getJsonStringFromMessage` changed, it now returns `ProtobufUtil::StatusOr` instead of `std::string`. Switching our code over to `getJsonStringFromMessageOrDie` which continues to return `std::string`.
- Increased the `no_output_timeout` parameter to 30m for test_gcc which was timing out.

Update Envoy to cfe0391 (Feb 5th 2021).

---

.bazelrc
MAINTAINERS.md

- Step by step guide on how to perform the update.
- Marking our local changes in `.bazelrc` with `#unique`. To make it easier to spot them.
- Reformatting `MAINTAINERS.md`, adding line breaks at 80 char where appropriate.

Documenting more details of the "Update Envoy" process.

---

include/nighthawk/common/BUILD
include/nighthawk/common/statistic.h
source/common/statistic_impl.cc
source/common/statistic_impl.h
test/statistic_test.cc

Being able to serialize and deserialize statistics serves several goals:
- Allow over-the-wire transportation in horizontally scaled setups.
- Facilitate storage of high res data.
- Could be used as a means to decouple our workers from the main thread,
by avoiding reliance on a shared process namespace to merge statistics.
(not a goal right now)
This adds an abstraction to Statistic, implements it for HdrHistogram, and
adds some tests.
Part of horizontal scaling effort, split out from:
Split out from https://github.com/oschaaf/nighthawk/tree/horizontal-scaling

Stats: Hdr histogram serialization/deserialization

---

ci/do_ci.sh
source/client/benchmark_client_impl.cc
source/client/benchmark_client_impl.h
test/benchmark_http_client_test.cc
test/integration/configurations/nighthawk_https_origin.yaml
test/integration/test_integration_basics.py

- don't set up a drain callback when there are no active connections
- set up a timer that will cap the amount of time we wait for the pool
to drain.
- disable latency measurement when commencing the drain procedure, as
by that time we are no longer interested in it, and in particular
don't want to hear about any warnings issued by the Statistic
implementation about recorded values being too large. 
Fixes #627

Fix potential hangs on exit & cap drain wait time

---

source/adaptive_load/adaptive_load_client_main.cc
test/adaptive_load/adaptive_load_client_main_test.cc

clang-tidy: address complaints

---

ci/docker/Dockerfile-nighthawk-benchmark

When invoking `ci/docker/benchmark_build.sh`, the image build fails for me with:
```
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
python3-3.8.7-r1:
breaks: world[python3=3.8.7-r0]
The command '/bin/sh -c apk add --no-cache docker=20.10.3-r0 openrc=0.42.1-r19 python3=3.8.7-r0' returned a non-zero code: 1
```
The change in this PR updates the Dockerfile to ensure that the python version listed is the minimum required version.
With this change in place, the docker image build script completes successfully:
```bash
$ ci/docker/benchmark_build.sh
...
Step 8/11 : RUN apk add --no-cache docker=20.10.3-r0 openrc=0.42.1-r19 python3>=3.8.7-r0
---> …
```

Fix python dependency version for NightHawk Benchmark image

---

test/server/http_test_server_filter_integration_test.cc

Recommend not to check for strict equality on error messages. This is aligned with [Google Cloud APIs error model](https://cloud.google.com/apis/design/errors#error_messages).
We are considering adding extra debug information to the underlying JSON parser library. The extra debug information breaks this test if it checks for strict equality.
Signed-off-by: Teju Nareddy <nareddyt@google.com>

Remove strict equality for error message

---

.bazelrc
.circleci/config.yml
bazel/repositories.bzl
ci/do_ci.sh
ci/run_envoy_docker.sh
source/client/process_impl.cc
test/output_transform_main_test.cc

- Sync `.bazelrc` from Envoy's repository.
- Sync `ci/run_envoy_docker.sh` from Envoy's repository.
- Update docker image version in `.circleci/config.yml`.
- The constructor of `ClusterManagerFactory` now requires an instance of `Envoy::Server::Options`. Satisfy it with `Envoy::OptionsImpl::OptionsImpl` (https://github.com/envoyproxy/envoy/commit/42af11e3ed3e50391dc0164c445d29d52a695267).
- An instance of `Envoy::Event::Dispatcher` now needs to be explicitly shut down on the main thread. (https://github.com/envoyproxy/envoy/commit/114d5aea7b05ef697d4fcd94201fe090a19077b7).
- adjusting coverage threshold from `94.3` to `94.2`.
- fixing a `clang_tidy` issue in `output_transform_main_test.cc`.

Update Envoy to f9301ff (Feb 26th 2021).

---

bazel/repositories.bzl

Following instructions from https://github.com/envoyproxy/nighthawk/blob/main/MAINTAINERS.md#updates-to-the-envoy-dependency 
- Updated Envoy Commit and Envoy_sha in repositories.bzl.
- bazelrc, bazelversion, docker.sh remain unchanged.

Update Envoy to 23a43b2 (March 1st, 2021)

---

api/client/service.proto
api/sink/BUILD
api/sink/sink.proto
include/nighthawk/common/BUILD
include/nighthawk/common/nighthawk_sink_client.h
source/common/BUILD
source/common/nighthawk_sink_client_impl.cc
source/common/nighthawk_sink_client_impl.h
test/common/BUILD
test/common/nighthawk_sink_client_test.cc

Add the proto definition for the sink service plus a client implementation and test.

Sink service client & unit tests

---

MAINTAINERS.md
README.md
bazel/repositories.bzl
source/client/options_impl.cc
source/common/request_source_impl.cc
test/integration/integration_test_fixtures.py
test/integration/test_integration_basics.py

- `.bazelrc` was unchanged
- `.circleci/config.yml` was unchanged
- `.bazelversion` was unchanged
- `ci/run_envoy_docker.sh` was unchanged
- Code changes
- Replace `factoryForGrpcService(..., Envoy::Grpc::AsyncClientFactoryClusterChecks::Skip)` with `factoryForGrpcService(..., /*skip_cluster_check=*/true)` due to PR #15449 in Envoy
- Delete test `test_nighthawk_client_v2_api_explicitly_set` and `test_nighthawk_test_server_envoy_deprecated_v2_api` in `test/integration/test_integration_basics.py` since they are broken by Envoy PR #15481
- Delete test fixture `http_test_server_fixture_envoy_deprecated_v2_api` in `test/integration/integration_test_fixtures.py`
- Update MAINTAINERS.md

Update Envoy to 031f75d (Mar 14th 2021)

---

WORKSPACE

The following gets emitted in the output of the build process:
```
DEPRECATED: the pip_repositories rule has been replaced with pip_install,
please see rules_python 0.1 release notes
```
This change stops that. It seems we no longer need it:
https://github.com/bazelbuild/rules_python/commit/8537cea11d867333c07c465d536778c1b7560cde

Remove pip_repositories usage.

---

docs/root/examples/HEADER_BASED_LATENCY.md

Another example, to make it easier to discover how to accomplish
tracking of latency communicated through response headers when
using Nighthawk.

doc example: header based latency tracking

---

include/nighthawk/sink/sink.h
source/sink/sink_impl.cc
source/sink/sink_impl.h
test/mocks/sink/mock_sink.h
test/sink/sink_test.cc

- Adds an in-memory sink. Comes in handy in tests, and could serve
a future role if we want to converge the way results are handled
in both distributed and non-distributed tests.
- Slightly refactors validation & testing to make it easier to see
what is specific to FileSinkImpl, making things a little more
natural in case someone else wants to  add a new sink type in the
future.
- Avoid MOCK_METHOD_N in the Sink mock as per recommendation.

Sink: add in memory sink, slightly refactor validation/testing.

---

api/client/options.proto
include/nighthawk/client/BUILD
include/nighthawk/client/options.h
source/client/BUILD
source/client/options_impl.cc
source/client/options_impl.h
test/mocks/client/mock_options.h

Another prelude to distributed test execution. Being able to
identify executions and associate results is going to come in
handy.
Also, this separates some BUILD targets to allow for a leaner build
process of future things that are going to depend on it.

Add execution-id & separate the options BUILD targets

---

test/sink/sink_test.cc

FileSinkTest.CorruptedFile would flake when running multiple
instances of it concurrently. This PR tweaks it to avoid that.

Sink tests: fix for parallel test execution

---

.bazelrc
bazel/repositories.bzl

Followed instructions from: https://github.com/envoyproxy/nighthawk/blob/main/MAINTAINERS.md#updates-to-the-envoy-dependency 
Tests passed, no changes required.

Update Envoy to 2858cd2 (April 06th 2021)

---

ci/do_ci.sh

Add aarch64 Bazel build options for GCC toolchain
which would enable the test_gcc for ci script on
arm platform.
Signed-off-by: trevor tao <trevor.tao@arm.com>

Enable test_gcc on arm64 platform for ci

---

.bazelrc
.circleci/config.yml
bazel/repositories.bzl
test/server/http_dynamic_delay_filter_integration_test.cc
test/server/http_filter_base_test.cc
test/server/http_filter_integration_test_base.cc
test/server/http_test_server_filter_integration_test.cc
test/server/http_time_tracking_filter_integration_test.cc

- Sync .bazelrc
- Update Docker image version in .circleci/config.yml
- ci/run_envoy_docker.sh was unchanged
- Code changes
- Remove `response->waitForEndStream();` from `HttpFilterIntegrationTestBase::getResponse()` in test/server/http_filter_integration_test_base.cc due to https://github.com/envoyproxy/envoy/pull/15972. We can't simply change it to `ASSERT_TRUE(response->waitForEndStream());` in `HttpFilterIntegrationTestBase::getResponse()` since this will cause error:
```
test/server/http_filter_integration_test_base.cc:69:5: error: no viable conversion from returned value of type 'void' to function return type 'Envoy::IntegrationStreamDecoderPtr' (aka 'unique_ptr<Envoy::IntegrationStreamDecoder>')
ASSERT_TRUE(response->waitForEndStream());
```
- Added …

Update Envoy to 751be72 (April 19th 2021)

---

api/adaptive_load/adaptive_load.proto
source/adaptive_load/adaptive_load_controller_impl.cc
source/adaptive_load/session_spec_proto_helper_impl.cc
test/adaptive_load/BUILD
test/adaptive_load/adaptive_load_controller_test.cc
test/adaptive_load/session_spec_proto_helper_test.cc

Allows the user to specify a cooldown period to wait for between individual benchmarks executed by the adaptive load controller. Useful in situations where cooldown is required to allow previously used connections to time out.
Also ensuring all durations in the adative session spec are validated.

Optional cooldown between benchmarks done by the adaptive controller.

---

api/adaptive_load/benchmark_result.proto
source/adaptive_load/BUILD
source/adaptive_load/adaptive_load_controller_impl.cc
test/adaptive_load/adaptive_load_controller_test.cc
test/common/fake_time_source.cc
test/common/fake_time_source.h
test/common/fake_time_source_test.cc
test/stopwatch_test.cc

This will allow users of the adaptive load controller to correlate statistics collected from the system under test with individual benchmark stages (adjusting stage, testing stage).
Done here:
- updated the `FakeIncrementingMonotonicTimeSource` to also support incrementing system time.
- renamed `FakeIncrementingMonotonicTimeSource` to `FakeIncrementingTimeSource`, since it is no longer specific just to the monotonic time.
- added new methods that allow resetting the `FakeIncrementingTimeSource` to a specific epoch value. 
- added start and end time to the `BenchmarkResult` message and populating them while the adaptive controller executes.

Store the start and end time of each benchmark done by the adaptive load controller.

---

.bazelrc
.circleci/config.yml
bazel/repositories.bzl

- Sync .bazelrc
- Update bazel/repositories.bzl
- disable test_gcc due to #686 

Update Envoy to c5833f2 (May 17th 2021)

---

bazel/repositories.bzl
source/client/process_impl.cc
source/common/uri_impl.cc

- Changing a `bool` to `envoy::config::core::v3::DnsResolverOptions` in calls to `Envoy::Event::Dispatcher::createDnsResolver` to match a recent Envoy change (https://github.com/envoyproxy/envoy/commit/2c0e1f21837fdf78cc91d2eb8c3735731d510f7e).

Update Envoy to 2c0e1f2 (Jun 2nd 2021).

---

bazel/repositories.bzl
source/client/benchmark_client_impl.cc
source/client/benchmark_client_impl.h
test/benchmark_http_client_test.cc

Changing how the HTTP connection pool is accessed after it was moved behind a new class `HttpPoolData` in Envoy (https://github.com/envoyproxy/envoy/commit/ff2c0e517c8677dd1c553e1c6ef55d2b14cdd996).
- Borrowing a temporary hack originally proposed by @yanavlasov in PR #693 which accesses the pool by defining a local class that happens to be a friend of `HttpPoolData`.

Update Envoy to ff2c0e5 (Jun 2 2021).

---

bazel/repositories.bzl
source/sink/service_impl.cc
source/sink/service_impl.h
test/adaptive_load/adaptive_load_client_main_test.cc
test/request_source/request_source_plugin_test.cc

After envoy switched to the true abseil type of string_view (https://github.com/envoyproxy/envoy/commit/72bf41fb0ecc039f196be02f534bfc2c9c69f348), we can no longer assign `absl::string_view` to `std::string`. Changing Nighthawk code accordingly.

Update Envoy to 72bf41f (Jun 04, 2021).

---

source/client/service_impl.h
test/integration/integration_test_fixtures.py

Integration tests that are using the "dummy-request-source" service implementation had a race on logging which was causing `tsan` test runs to be excessively flaky.
- Improve logging when the GRPC service reports an error in integration tests. Previously we would just get an assertion failure without context.
- Create a logging lock when constructing the `RequestSourceServiceImpl`. If not done here, the log creation is racy as it happens at the first call to `ENVOY_LOG`.
Fixes #697.

Fix a race in integration tests.

---

bazel/repositories.bzl
source/client/BUILD
source/client/benchmark_client_impl.cc
source/client/benchmark_client_impl.h
source/client/process_impl.cc

- Removing reference to header file `transport_sockets/well_known_names.h` that was deleted by Envoy (https://github.com/envoyproxy/envoy/commit/97d4792449b9c42d6d2f6d727f7cc47ee20d2243).
- Undoing temporary workaround for Nighthawk's pool access now that https://github.com/envoyproxy/envoy/pull/16865 was merged in.
Fixes #695.

Update Envoy to 14cca0a (Jun 08, 2021).

---

test/integration/BUILD
test/integration/test_connection_management.py

- decrease the number of requests per connection in `test_connection_management`. This almost guarantees that multiple connections will be used as the test expects.
- ensure that `test_request_source` has the testdata it needs.

Fix local execution of the python integration tests.

---

ci/do_ci.sh
test/integration/test_connection_management.py
test/integration/test_integration_basics.py
test/integration/unit_tests/BUILD
test/integration/unit_tests/test_utility.py
test/integration/utility.py

In `test_integration_basics.py`:
- add a test utility that can retrieve the actual execution duration.
- increase the test duration to 5 and 10 seconds from 1 and 3 seconds.
- no longer expecting Nighthawk to execute for exactly the prescribed duration, instead calculating the number of expected requests / etc based on the actual execution duration. Still expecting that duration to be positive.
- adding a cooldown sleep between executions.
In `test_connection_management.py`:
- disabling test expectation for the number of used connections in `test_http_h1_connection_management_2` as it remains excessively flaky even after #700. Also undoing the requests_per_connection tweak done in the same PR.
Verified with 10 successful executions.
Fixes #701.
Signed-off-by: Jakub Sobon …

Fixing flakes in the integration tests.

---

ci/do_ci.sh
test/integration/integration_test_fixtures.py
test/integration/test_integration_basics.py
test/integration/utility.py

These remain very flaky locally, but succeed in circleci.
Also:
- changing logs in the test fixture from debug to info. They aren't noisy, because pytest only includes them on failures, yet they are very helpful on those failures.

Skip mini stress test on local test executions.

---

.circleci/config.yml
ci/do_ci.sh

Building in multiple smaller bazel executions results in each of the executions having a smaller memory footprint.
Fixes #686.

Bringing test_gcc back by breaking the build into parts.

---

bazel/repositories.bzl

- Update bazel/repositories.bzl
- .bazelrc already in sync

Update Envoy to d3a9012 (July 07 2021)

---

bazel/repositories.bzl
source/client/benchmark_client_impl.cc
source/common/request_source_impl.cc
test/benchmark_http_client_test.cc

- no changes in `.bazelrc`, `.bazelversion` or `ci/run_envoy_docker.sh`.
- reverting the `addIdleCallback` connection pool method back to `addDrainedCallback` as per https://github.com/envoyproxy/envoy/pull/17319.
- changing method call `AsyncClientFactory::create()` to `AsyncClientFactory::createUncachedRawAsyncClient()` as per https://github.com/envoyproxy/envoy/pull/15745.

Update Envoy to ba474ac (Jul 19th 2021).

---

.bazelrc
bazel/repositories.bzl
source/client/benchmark_client_impl.cc
test/benchmark_http_client_test.cc

Replacing drainedCallback with idleCallback in benchmark_client_impl and benchmark_client_test.
Replacing auth_enabled with google_default_credentials in bazelrc
Signed-off-by: William Juan <66322422+wjuan-AFK@users.noreply.github.com>

Update Envoy to a066b5e (Aug 03th 2021)

---

ci/do_ci.sh

This prevents OOM when running `test_gcc`.
Also log the currently executed command in `run_on_build_parts` which helps with debugging of these errors.

Decrease the amount of memory bazel uses.

---

ci/do_ci.sh
extensions_build_config.bzl
test/integration/BUILD
test/integration/configurations/nighthawk_https_origin_quic.yaml
test/integration/integration_test_fixtures.py
test/integration/test_integration_basics.py

Done here:
- Creating a Quic specific test fixture that changes the target IP address used by the Nighthawk client in e2e tests to loopback to avoid the following Quic error:
```
[01:33:37.413994][1494720][I] Client: Error: QUIC_DECRYPTION_FAILURE detail: Unable to decrypt ENCRYPTION_HANDSHAKE header protection (missing key).
```
- Improving how the Nighthawk client arguments are logged in e2e tests to simplify copy&pasting while debugging.
- Defining a single BUILD filegroup that contains all the test server configs and adding `nighthawk_https_origin_quic.yaml` for the HTTP/3 Quic e2e test.
- Adding the `envoy.access_loggers.file` extension to the Nighthawk build, this  extension is required to avoid a deprecation warning about the  `admin/access_log_path` field in the new test server …

[QUIC 060]: Adding an e2e test that uses HTTP/3 Quic.

---

docs/root/overview.md
extensions_build_config.bzl
source/client/process_bootstrap.cc
test/integration/BUILD
test/integration/configurations/nighthawk_https_origin_quic.yaml
test/integration/integration_test_fixtures.py
test/integration/test_integration_basics.py
test/process_bootstrap_test.cc

Nitghhawk now generates correct bootstrap configuration when HTTP/3 Quic is requested as the upstream protocol.
Integration tests will be added in the next PR. Quic functionality was verified locally at this PR.
Works on #23

[QUIC 050]: Adding bootstrap generation support for HTTP/3 Quic.

---

docs/root/overview.md
extensions_build_config.bzl
source/client/process_bootstrap.cc
test/integration/BUILD
test/integration/configurations/nighthawk_https_origin_quic.yaml
test/integration/integration_test_fixtures.py
test/integration/test_integration_basics.py
test/process_bootstrap_test.cc

Envoy marked two fields that we were using as deprecated:
1. The `http2_protocol_options` field is [deprecated](https://github.com/envoyproxy/envoy/blob/1260c5c2d1c5b85639a8e566a6b153198ddbf109/api/envoy/config/cluster/v3/cluster.proto#L801-L808) in favor of the common message `HttpProtocolOptions`. Migrating us to the new field simplifies the implementation of HTTP/3 Quic which also uses this message.
2. The `max_requests_per_connection` field is [deprecated](https://github.com/envoyproxy/envoy/blob/1260c5c2d1c5b85639a8e566a6b153198ddbf109/api/envoy/config/cluster/v3/cluster.proto#L751-L753) in favor of the `HttpProtocolOptions.max_requests_per_connection` field.
This PR contains no changes to functionality.
Works on #23

[QUIC 040]: Migrating off deprecated fields in the bootstrap.

---

docs/root/overview.md
extensions_build_config.bzl
source/client/BUILD
source/client/process_bootstrap.cc
source/client/process_bootstrap.h
source/client/process_impl.cc
source/client/process_impl.h
test/BUILD
test/integration/BUILD
test/integration/configurations/nighthawk_https_origin_quic.yaml
test/integration/integration_test_fixtures.py
test/integration/test_integration_basics.py
test/process_bootstrap_test.cc
test/test_common/BUILD
test/test_common/proto_matchers.cc
test/test_common/proto_matchers.h

Having the code in its own library not only allows to test it, but it also provides documentation of how various Nighthawk options translate to the public Envoy API.
No functional changes in this PR except for changing the return value to absl::StatusOr (i.e. the code no longer throws).
Done here:
- adding a test utility that compares proto messages and prints diffs.
- moving the bootstrap generation code into its own library.
- adding unit tests for the major behaviors of the bootstrap generation code.
Works on #23

[QUIC 020]: Moving code that creates the Envoy bootstrap into its own library.

---

test/mocks/adaptive_load/mock_metrics_evaluator.h
test/mocks/adaptive_load/mock_session_spec_proto_helper.h
test/mocks/client/mock_benchmark_client.h
test/mocks/client/mock_benchmark_client_factory.h
test/mocks/client/mock_options.h
test/mocks/common/mock_nighthawk_service_client.h
test/mocks/common/mock_platform_util.h
test/mocks/common/mock_rate_limiter.h
test/mocks/common/mock_request_source.h
test/mocks/common/mock_request_source_factory.h
test/mocks/common/mock_sequencer.h
test/mocks/common/mock_sequencer_factory.h
test/mocks/common/mock_termination_predicate.h
test/mocks/common/mock_termination_predicate_factory.h
test/sequencer_test.cc

* Use more `MOCK_METHOD` instead of `MOCK_METHODn`.
* Add the `override` qualifier where appropriate.
This PR is based on some automated changes suggested by @mum4k with tweaks to remove some `override`s that failed to build.
Co-authored-by: Jakub Sobon <mumak@google.com>

test: More MOCK_METHOD modernization.

---

.bazelrc
.circleci/config.yml
.clang-tidy
bazel/repositories.bzl
ci/run_clang_tidy.sh
test/integration/configurations/sni_origin.yaml

- synced changes in `.bazelrc`.
- updated the `envoyproxy/envoy-build-ubuntu` in `.circleci/config.yml`.
- no changes in `.bazelversion` or `run_envoy_docker.sh`.
- renamed deprecated 'envoy.listener.tls_inspector' to 'envoy.filters.listener.tls_inspector' in the integration test configuration.
- removed date from `.circleci/config.yml` since it is outdated and likely to get outdated again on future updates. It is unclear what value it adds since the version is just mechanically synced from the Envoy repository.
- disabling the `bugprone-narrowing-conversions` clang-tidy check which started reporting errors at this PR and filing https://github.com/envoyproxy/nighthawk/issues/750.

Update Envoy to 54b686b (Oct 4th 2021).

---

.bazelrc
bazel/repositories.bzl
source/client/stream_decoder.h

- updates to `.bazelrc`
- rename of decode100ContinueHeaders to decode1xxHeaders according to envoyproxy/envoy#18904

Update envoy to a6fc192

---

bazel/repositories.bzl

Simple update
- .bazelrc not updated since Nov 12

Update Envoy to 1143dd7 (Nov 29, 2021)

---

test/integration/test_integration_basics.py

At low resources, nighthawk is not guaranteed to distribute requests evenly among all backends. Loosens requirement to all backends must receive some traffic. 
In addition, removed the total_2xx constraint as that is verifying the same behavior as test_http_h1_termination_predicate.
closes #766 

Loosen requirements on test_multiple_backends_http_h1

---

test/integration/test_integration_basics.py

Changed the test to check logs for evidence of drain timeout. 
Also increased the execution time to 30 seconds as 3 seconds  has historically been short in CI and might risk no client being sent out. 
Note that this approach isn't perfect. We are relying on the evidence of logs which is brittle and we are relying on always hitting the drain timeout. It is possible that the pool drains fast enough to not produce the log message. 
closes #771 

Reduce dependency on time in test_drain integration test

---

test/integration/test_integration_basics.py

Tests are failing without sending traffic. Increasing the duration of the test to allow more time for nighthawk to get started. In an ideal environment, increase duration should not increase the necessary test time as nighthawk should terminate once it receives a single 2xx response.
closes #775 

Increase duration of TLS tests and remove h2 deprecation warning

---

test/integration/test_integration_basics.py

Disabling the test due to #773. Proper fix would entail fixing execution_duration code to properly measure time where traffic was generated.

Disable test_http_request_release_timing in circle CI 

---

test/adaptive_load/adaptive_load_client_main_test.cc

The Protobuf DebugString format is an unstable format and it may be different from the Protobuf TextFormat at some point in the future. To make this unit test more robust,  
we deserialize the text proto (in TextFormat) from the golden file first, and then compare the DebugString of that deserialized proto with the actual value (a DebugString).

Avoid compare Protobuf TextFormat with Protobuf DebugString

---

test/integration/test_connection_management.py
test/integration/test_integration_basics.py
test/integration/unit_tests/test_utility.py
test/integration/utility.py

Splits test_h1_pool_strategy integration test into two separate tests for better granularity. 
Relax the constraints of each test to be more resilient to a variation of requests sent while still verifying the behavior of the connection pool strategies. 
Increased the duration of each test to also improve the overall stability of traffic sent by nighthawk. 
closes #769 

Split test_h1_pool_strategy into LRU and MRU tests and relax constraints

---

test/integration/test_integration_basics.py

Some H1 tests currently fail due to having more connections than expected.  
Example: https://circleci.com/api/v1.1/project/github/envoyproxy/nighthawk/30668/output/102/0?file=true&allocation-id=61aa3f06f34d7762fa437b4c-0-build%2F25476C95
Relaxing constraints as for H1, new connections maybe created if clients cannot keep up with the existing request rate. 
See https://github.com/tomjzzhang/envoy/blob/a6fc192705b7a55ebef5b534cfac522a6c54af83/source/common/conn_pool/conn_pool_base.cc#L245
Also relaxing constraints in test_multiple_backends_https_h1 to match test_multiple_backends_http_h1 as fully equitable round robin is not guaranteed by nighthawk. 

Relax connection constraints on H1 tests to reduce flakiness

---

BUILD
api/request_source/BUILD
include/nighthawk/distributor/BUILD
source/distributor/nighthawk_distributor_client_impl.h
test/server/configuration_test.cc

Done here:
- exporting the main LICENSES file.
- not referring to Nighthawk's code as if it was external.
- fixing bad include prefix and import of Nighthawk's distributor API.
- removing implicit conversions of strings to booleans.

A collection of fixes that simplify import of Nighthawk into Google.

---

test/integration/test_integration_basics.py

Noticed that some runs are failing due to not receiving the expected amount of counters. 
Example:
https://app.circleci.com/pipelines/github/envoyproxy/nighthawk/3411/workflows/4f3cc2a5-8f41-4cf0-b75c-183c63a1eb8d/jobs/31198
Expected 12, Received 14.  The two unaccounted counters are benchmark.pool_overflow and upstream_rq_pending_overflow which is an acceptable outcome of the test. Therefore relaxing test constraints. 

Relax unnecessarily strict counter assertion

---

bazel/repositories.bzl

- updated bazel/repositories.bzl
- .bazelrc already in sync
- no code changes

Update Envoy to f67be30 (Jan 10, 2022)

---

.bazelrc
README.md
bazel/repositories.bzl

- syncing `.bazelrc` from Envoy (https://github.com/envoyproxy/envoy/pull/19468).
- no changes in `.bazelversion`, `run_envoy_docker.sh`, `gen_compilation_database.py`.

Update envoy to 7174c14 (January 19, 2022).

---

bazel/repositories.bzl

- no changes in `.bazelrc`, `.bazelversion`, `run_envoy_docker.sh`, `gen_compilation_database.py`.
- no code changes were necessary.

Update envoy to 4b38a99 (January 25, 2022).

---

bazel/repositories.bzl

This was a simple update. 
Confirmed that Envoy's .bazelrc is unchanged since `commit 4f58f018007d9752b67e9b00c5713f862a4fa77c Date:   Thu Jan 13 15:59:27 2022 -0500`.

Update Envoy to aa29229 (Jan 31, 2022)

---

README.md
api/client/options.proto
include/nighthawk/client/options.h
source/client/options_impl.cc
source/client/options_impl.h
source/client/process_bootstrap.cc
test/integration/test_integration_basics.py
test/mocks/client/mock_options.h
test/options_test.cc
test/process_bootstrap_test.cc

Allows Nighthawk users to specify a custom upstream bind config, i.e. to indicate the source address, port and socket options to be used when sending requests.

Support specifying a custom upstream bind config.

---

source/server/http_dynamic_delay_filter.cc
source/server/http_dynamic_delay_filter.h
source/server/http_filter_config_base.cc
source/server/http_filter_config_base.h
source/server/http_test_server_filter.cc
source/server/http_test_server_filter.h
source/server/http_time_tracking_filter.cc
source/server/http_time_tracking_filter.h
test/server/http_test_server_filter_integration_test.cc

Signed-off-by: wbpcode <wbphub@live.com>
To address #808.
The filter config is shared by mutiple filter instances in different workers. In the original logic, the `computeEffectiveConfiguration` may updates the `effective_config_` field of filter config. This operations are unsafe for mutiple threads scenarios.

fix nighthawk crash error when run server with concurrency >1

---

bazel/repositories.bzl
tools/check_format.sh

- no changes in `.bazelrc`, `.bazelversion`, `ci/run_envoy_docker.sh` or `tools/gen_compilation_database.py`.
- introducing a workaround for our use of the Envoy's `check_format.py` after https://github.com/envoyproxy/envoy/pull/20108. See https://github.com/envoyproxy/nighthawk/issues/815 for details.

Update Envoy to d3bd9bb (Mar 7th 2022).

---

README.md
api/client/options.proto
include/nighthawk/client/BUILD
include/nighthawk/client/options.h
source/client/options_impl.cc
source/client/options_impl.h
source/client/process_bootstrap.cc
test/mocks/client/mock_options.h
test/options_test.cc
test/process_bootstrap_test.cc

New flag --stats-flush-interval-duration is mutually exclusive with --stats-flush-interval.

Add a CLI flag --stats-flush-interval-duration to allow specifying stats flush interval in Duration

---

bazel/repositories.bzl

- Update the `ENVOY_COMMIT` and `ENVOY_SHA` in bazel/repositories.bzl
- .bazelrc already in sync
Signed-off-by: qqustc <qqin@google.com>

Update Envoy to 47d09cc (Mar 28 2022)

---

.azure-pipelines/bazel.yml
.azure-pipelines/pipelines.yml

This is first of a few PRs that will migrate Nighthawk's CI to Azure Pipelines. This is what Envoy uses currently and this is where we can get more resources which will enable the integration tests to pass again.
This defines a single step `build` that will execute in our `nighthawk-presubmit` pipeline.
Works on #820.

Defining our first Azure Pipeline.

---

.azure-pipelines/bazel.yml
.azure-pipelines/pipelines.yml
ci/do_ci.sh

Also enabling local bazel cache to carry state between the CI steps and printing out the full bazel command line for debugging.
Works on #820.

Adding the test step into AZP

---

.azure-pipelines/pipelines.yml
ci/do_ci.sh
ci/run_clang_tidy.sh
test/BUILD

- Decreasing integration test coverage threshold from `75%` to `74.2%`. The integration test coverage wasn't executing on CircleCI due to memory limitations. Our coverage dropped despite my attempts to execute this locally before each submission. While I did verify that the tests passed locally, I did not notice that the script is unable to verify the coverage when compiling on RBE. Also removing a TODO linked to #564 which doesn't appear to be relevant anymore.
- Modified `ci/do_ci.sh` so that clang_tidy uses all available CPUs when executing on AZP. Included a logging statement that prints this out in the output for debugging.
- Setting a larger bazel timeout for the `python_test` that runs all our integration tests to avoid hitting the timeout on test execution.
Works on #820. …

Adding all our CI jobs to AZP.

---

.bazelrc
bazel/repositories.bzl
test/integration/test_integration_basics.py

- updated `.bazelrc` based on https://github.com/envoyproxy/envoy/pull/20852 and https://github.com/envoyproxy/envoy/pull/20813. Disabling platform mappings in our configuration, since we don't need them.
- no changes in `.bazelversion`, `ci/run_envoy_docker.sh` or `tools/gen_compilation_database.py`.
- switching integration tests that verify custom TLS configuration to another two ciphers that are supported in the default Envoy server configuration after https://github.com/envoyproxy/envoy/pull/20643.

Update Envoy to 569f239 (Apr 18th 2022).

---

tools/format_python_tools.py
tools/gen_compilation_database.py

Keeping this file in sync with the Envoy version is part of our regular maintenance. However spotting differences has been made harder after our tools reformatted `tools/gen_compilation_database.py`.
Done here:
- copying `tools/gen_compilation_database.py` to adopt the original formatting.
- manually changing the lines that were marked unique.
- modifying our formatting tools, so that `tools/gen_compilation_database.py` gets skipped.

Adopt Envoy's formatting in tools/gen_compilation_database.py.

---

.azure-pipelines/bazel.yml
.azure-pipelines/pipelines.yml
MAINTAINERS.md
ci/do_ci.sh
ci/docker/benchmark_azp_push.sh
ci/docker/docker_azp_push.sh
ci/run_envoy_docker.sh

Temporarily forking the `docker_push.sh` and `benchmark_push.sh` scripts to AZP specific versions as a simplification. The CircleCI versions will be cleared when we turn down the CircleCI pipeline. Adding new step `do_docker_azp` to `ci/do_ci.sh` to execute the forked scripts.
Modified `ci/run_envoy_docker.sh` to forward variables required by the docker scripts. Since we regularly copy this script from Envoy, the custom lines are marked as `# unique` and the maintenance steps in `MAINTAINERS.md` are updated to indicate the presence of these unique lines.
Works on #820.

Migrate our docker workflow to AZP.

---

README.md

Addresses concerns raised in #832 and #833.

Updating instructions on how to build Nighthawk.

---

ci/do_ci.sh
test/integration/test_integration_basics.py
test/integration/utility.py

These were disabled previously and were incorrectly enabled in #837.
They will execute in AZP CI.
Fixes #842.
Verified that they are skipped locally:
```
[gw1] [ 25%] SKIPPED test/integration/test_integration_basics.py::test_http_h2_mini_stress_test_open_loop[IpVersion.IPV4]
[gw0] [ 31%] SKIPPED test/integration/test_integration_basics.py::test_http_h1_mini_stress_test_open_loop[IpVersion.IPV4]
```
And are [executed in AZP](https://dev.azure.com/cncf/envoy/_build/results?buildId=106921&view=logs&s=859b8d9a-8fd6-5a5c-6f5e-f84f1990894e&j=a10fa2d5-ad16-525d-3f64-d3c7d0f53774):
```
[gw1] [ 66%] PASSED ../../../../../../../../../../../../../../../source/test/integration/test_integration_basics.py::test_http_h2_mini_stress_test_open_loop[IpVersion.IPV4] 
[gw0] [ 77%] PASSED …
```

Disable integration tests that cannot execute locally.

---

.bazelrc
bazel/repositories.bzl
source/client/process_impl.cc

- Envoy's `.bazelrc` reordered the tools paths on macOS
- `Envoy::Http::Http1::ActiveClient` 1-arg constructor was removed; migrated to the 2-arg constructor with the second arg `absl::nullopt` 

Update Envoy to 84b6682 (May 23, 2022)

---

bazel/repositories.bzl

- no changes to `.bazelrc`, `.bazelversion`, `run_envoy_docker.sh` or `tools/gen_compilation_database.py`.

Update Envoy to c92c032 (Jun 13th 2022).

---

bazel/repositories.bzl

- Update bazel/repositories.bzl
- .bazelrc, .bazelversion, tools/gen_compilation_database.py already in sync
Signed-off-by: Qin Qin <qqin@google.com>

Update Envoy to 3e3721f (June 27th 2022)

---

README.md
api/client/options.proto
include/nighthawk/client/options.h
source/client/options_impl.cc
source/client/options_impl.h
source/client/process_bootstrap.cc
test/integration/test_integration_basics.py
test/mocks/client/mock_options.h
test/options_test.cc
test/process_bootstrap_test.cc

Allows Nighthawk users to specify custom HTTP3 protocol options. Only valid when running with `--protocol http3`.
Signed-off-by: Jakub Sobon [mumak@google.com](mailto:mumak@google.com)

Support specifying custom HTTP3 protocol options.

---

.azure-pipelines/pipelines.yml
source/client/service_impl.h

Also re-enable `text_gcc`.
Fixes #872.
**Details**:
- `ServiceImpl` creates `Envoy::Logger::Context` which requires `Envoy::Thread::MutexBasicLockable`.
- The `Envoy::Thread::MutexBasicLockable` was constructed after the `Envoy::Logger::Context`, so `Envoy::Logger::Context` became invalid during destruction of `ServiceImpl`.
- this PR ensures that `Envoy::Thread::MutexBasicLockable` lives longer than `Envoy::Logger::Context`.
- Fixing the same problem in the construction of `RequestSourceServiceImpl`.
**Reason for `test_gcc` failure:**
- https://github.com/envoyproxy/envoy/pull/21884 triggered this bug, because it added a logging call initiated indirectly from the destructor of `Envoy::ProcessWide`.
- This logging call happened during the destruction of `ServiceImpl` when the …

Fix construction order of `ServiceImpl` and `RequestSourceServiceImpl`.

---

requirements.txt

Also, set it up so that we take in non-major version updates.
Updating pytest and request required adding in new dependencies.
This address some of the problems in https://github.com/envoyproxy/nighthawk/issues/819.

Update python dependencies to their latest version.

---

MAINTAINERS.md
requirements.txt

Documentation includes:
1. Added step to check for python dependencies once a month when updating envoy.
2. Included documentation for how to find python dependency updates.
3. Included a section on identifying a class of errors as needing a new dependency, which was part of what made #819 more confusing.

Create documentation for finding major dependency updates

---

test/BUILD
test/options_test.cc

In some environments, whitespace differences cause these tests to fail.
String matching is less stable than the proto matchers that we now have.
Works on #433 

Use proto matcher instead of debug_string matching for protos.

---

test/adaptive_load/BUILD
test/adaptive_load/adaptive_load_controller_test.cc
test/adaptive_load/fake_plugins/fake_input_variable_setter/BUILD
test/adaptive_load/fake_plugins/fake_input_variable_setter/fake_input_variable_setter_test.cc
test/adaptive_load/fake_plugins/fake_metrics_plugin/BUILD
test/adaptive_load/fake_plugins/fake_metrics_plugin/fake_metrics_plugin_test.cc
test/adaptive_load/fake_plugins/fake_step_controller/BUILD
test/adaptive_load/fake_plugins/fake_step_controller/fake_step_controller_test.cc
test/adaptive_load/input_variable_setter_test.cc
test/adaptive_load/metrics_evaluator_test.cc
test/adaptive_load/scoring_function_test.cc
test/adaptive_load/step_controller_test.cc
test/common/BUILD
test/common/nighthawk_service_client_test.cc
test/distributor/BUILD
test/distributor/nighthawk_distributor_client_test.cc
test/request_source/BUILD
test/request_source/request_source_plugin_test.cc
test/sink/BUILD
test/sink/nighthawk_sink_client_test.cc
test/sink/sink_service_test.cc

Remove all instances of using DebugString in tests to compare protos

---

include/nighthawk/adaptive_load/BUILD
include/nighthawk/adaptive_load/metrics_evaluator.h
include/nighthawk/adaptive_load/metrics_plugin.cc
include/nighthawk/adaptive_load/metrics_plugin.h
source/adaptive_load/metrics_evaluator_impl.cc
source/adaptive_load/metrics_evaluator_impl.h
test/adaptive_load/fake_plugins/fake_metrics_plugin/fake_metrics_plugin.cc
test/adaptive_load/fake_plugins/fake_metrics_plugin/fake_metrics_plugin.h
test/adaptive_load/metrics_evaluator_test.cc
test/adaptive_load/metrics_plugin_test.cc
test/mocks/adaptive_load/mock_metrics_evaluator.h

Create new interface function to provide plugins with appropriate measuring period.
Provide default implementation to avoid breaking any existing clients. 
Try providing measuring period first, if it is unimplemented, fallback to old implementation. This way, external plugins can easily migrate to the new interface.
Fixes #798

Add new GetMetricByNameWithReportingPeriod function

---

test/options_test.cc

This helps unblock migration to a new json parser, if envoy uses it, as well as if other systems try to enforce it.

Relax expectations of INVALID_ARGUMENT errors for protobufs.

---

test/integration/nighthawk_test_server.py

n/nighthawk_test_server.py:198: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
[logging.warn("Process logged a warning: %s", w) for w in warnings]

Use logging.warning as logging.warn is deprecated.

---

bazel/repositories.bzl
test/adaptive_load/BUILD
test/common/BUILD
test/common/nighthawk_service_client_test.cc
test/distributor/BUILD
test/distributor/nighthawk_distributor_client_test.cc
test/sink/BUILD
test/sink/nighthawk_sink_client_test.cc
test/test_common/BUILD
test/test_common/mock_stream.h

- Update the ENVOY_COMMIT and ENVOY_SHA in [bazel/repositories.bzl](https://github.com/envoyproxy/nighthawk/blob/main/bazel/repositories.bzl) to the latest Envoy's commit.
- Recreate utility mock_stream classes due to https://github.com/envoyproxy/envoy/pull/22706 and https://github.com/grpc/grpc/pull/26641#issuecomment-1074338721

Update Envoy to c2fccb2 (Aug 22nd 2022)

---

benchmarks/BUILD
benchmarks/configurations/lds.yaml
benchmarks/configurations/request_source_five_clusters.json
benchmarks/dynamic_config_envoy_proxy.py
benchmarks/dynamic_test/test_cds_churn_with_traffic.py
test/integration/configurations/nighthawk_15_listeners_http_origin.yaml
test/integration/unit_tests/test_utility.py
test/integration/utility.py

Add a test that has 5 clusters, 3 endpoints each. Use `request-source-plugin-config` to configure client to target different backends.

CDS churn with multiple clusters with traffic

---

.bazelrc
bazel/repositories.bzl
source/adaptive_load/adaptive_load_controller_impl.cc
source/client/process_impl.cc
source/client/process_impl.h
source/client/stream_decoder.cc
source/sink/sink_impl.cc

- Envoy started calling some methods on `::Envoy::Server::Configuration::ServerFactoryContext` since https://github.com/envoyproxy/envoy/pull/23019. Done the following changes:
1. Renamed `NullServerInstance` to `NighthawkServerInstance` and `NullServerFactoryContext` to `NighthawkServerFactoryContext` since some of the methods now need to be implemented.
2. Improved PANIC messages in unimplemented methods on these objects, so that they mention the specific method that was called. This improved debugging of this kind of problems.
3. Implemented methods, which are now called by Envoy. The methods just forward pre-existing object instances.
- making sure we only format types that are 'formattable' in log messages as required by the new fmtlib imported in …

Update Envoy to f307e71 (Sep 13th 2022).

---

benchmarks/BUILD
benchmarks/run_benchmark.sh

Avoids building unnessary targets in `//benchmark/`

Only build py_binary targets in benchmark script.

---

source/adaptive_load/adaptive_load_controller_impl.cc
source/client/output_formatter_impl.cc
source/client/output_formatter_impl.h
source/client/process_impl.cc
source/client/stream_decoder.cc
source/sink/sink_impl.cc
test/BUILD
test/adaptive_load/fake_plugins/fake_metrics_plugin/fake_metrics_plugin.cc
test/adaptive_load/metrics_evaluator_test.cc
test/options_test.cc
test/output_formatter_test.cc
test/sink/nighthawk_sink_client_test.cc
test/test_common/mock_stream.h
tools/check_format.sh
tools/code_format/config.yaml

Fixes https://github.com/envoyproxy/nighthawk/issues/913
Direct changes:
- Modified config.yaml to not exclude the current directory, which was excluding all of NH
- Overrode some settings in config.yaml to move past some code changes
- Filed https://github.com/envoyproxy/nighthawk/issues/914 and https://github.com/envoyproxy/nighthawk/issues/915 to address these overrides in the future
- Moved include_dir_order from check_format.sh over to the config.yaml where it now needs to live.
Also ran the format script to fix all current code formatting errors.

Make the fix_format and check_format scripts work on Nighthawk code

---

.bazelrc
.vscode/README.md
bazel/repositories.bzl

- Update the ENVOY_COMMIT and ENVOY_SHA in [bazel/repositories.bzl](https://github.com/envoyproxy/nighthawk/blob/main/bazel/repositories.bzl) to the latest Envoy's commit.
- Update [.bazelrc](https://github.com/envoyproxy/nighthawk/blob/main/.bazelrc) to match Envoy commit https://github.com/envoyproxy/envoy/pull/23396
- Small typo fix.

Update Envoy to e5ec3da (Oct 10th 2022)

---

README.md
ci/do_ci.sh
include/nighthawk/client/options.h
source/client/options_impl.cc
source/client/options_impl.h
source/client/process_impl.cc
test/BUILD
test/mocks/client/mock_options.h
test/options_test.cc
test/process_test.cc

Adds in the scaffolding pieces of passing around user defined plugin options.
Deferring the actual use of the plugins to a later PR, in an effort to keep these PRs small/readable.

Pass user defined output plugin through to options.

---

MAINTAINERS.md
requirements.txt

Integration tests have been failing with an error that looks like:
```
2022-10-28T16:21:42.2524307Z INTERNALERROR>     from py.log import Producer
2022-10-28T16:21:42.2525457Z INTERNALERROR> ModuleNotFoundError: No module named 'py.log'; 'py' is not a package
```
Updating dependencies and adding in a dependency on `py` appears to address this failure.

Update python dependencies to new major versions

---

MAINTAINERS.md
WORKSPACE
bazel/repositories.bzl
ci/do_ci.sh
requirements.txt

Specifics:
- gen_compilation_database updated, but only in ways that we override
- https://github.com/envoyproxy/envoy/commit/ba81ae537e722ad99906599f5d3ad367ca854433 updates rules_python to 0.13.0
- Deprecates pip_install
- Requires pinning of everything in requirements.txt
- Now requires us to now call install_deps when workspace is loaded.

Update Envoy to 6b7c95d.

---

source/client/process_impl.cc

Our process code can throw NigthhawkException (e.g. incorrect request source config). The code currently doesn't log any information about it. This PR adds a logging statement for these cases.

Log and re-throw on NigthhawkException same as on EnvoyException.

---

README.md
source/client/options_impl.cc

In the README, proto it accepts uint64_t but we were using uint32_t for parsing -> out of range error for valid values

Minor fix: Correct int size for threshold, clarify readme.

---

.azure-pipelines/pipelines.yml
ci/do_ci.sh
test/run_nighthawk_bazel_coverage.sh

The PR splits the coverage AZP stage into two, so that we can publish two artifacts with unique names.

Upload coverage report as a pipeline artifact.

---

bazel/repositories.bzl
extensions_build_config.bzl
source/client/BUILD
source/client/process_impl.cc
tools/code_format/config.yaml

- Synced [tools/code_format/config.yaml](https://github.com/envoyproxy/nighthawk/blob/main/tools/code_format/config.yaml)
- define `MOBILE_PACKAGE_VISIBILITY = ["//:mobile_library"]` in `extensions_build_config.bzl` because of https://github.com/envoyproxy/envoy/pull/23935/
- include eds clusters extension in `extensions_build_config.bzl` because of https://github.com/envoyproxy/envoy/pull/23920/
- switch to `Envoy::OptRef<Envoy::Server::Admin>` per https://github.com/envoyproxy/envoy/pull/23903/ 
Signed-off-by: Qin Qin <qqin@google.com>

update Envoy to 8a26244 (2022-11-21)

---

api/client/output.proto
source/client/benchmark_client_impl.cc
source/client/benchmark_client_impl.h
test/benchmark_http_client_test.cc

Remove the counter that previously was intended to track these errors. This new solution provides more information to users and removes the weirdness of having a termination predicate that would only terminate after all work is done.

Change User Defined Output proto to have optional error status

---

source/user_defined_output/log_response_headers_plugin.cc

Align parameter names between .h and .cc files.

---

.azure-pipelines/pipelines.yml
ci/do_ci.sh

Include the `System.JobAttempt` in the artifact name to ensure unique artifact names for each retry.
Fixes #960 

Allow pipeline retries after artifacts were published.

---

bazel/repositories.bzl
requirements.txt
test/mocks/common/mock_termination_predicate.h

- Manually checked:
- `.bazelrc`
- `.bazelversion`
- `ci/run_envoy_docker.sh`
- `tools/gen_compilation_database.py`
- `tools/code_format/config.yaml`
- Updated `requirements.txt`
- Note: During the [update procedure](https://github.com/envoyproxy/nighthawk/blob/main/MAINTAINERS.md#finding-python-dependencies), discovered that the previous `charset_normalizer==3.0.0` was actually unusable; reduced it to `charset_normalizer==2.1.1`

Update Envoy to f3edd6d (Jan 10, 2023)

---

source/client/process_impl.cc
source/client/process_impl.h
test/benchmark_http_client_test.cc
test/factories_test.cc
test/sequencer_test.cc
test/statistic_test.cc

Prepared with the help of @jmarantz, see https://github.com/envoyproxy/envoy/issues/24007.

Remove dependency on the implicit cast of Stats::Store to Stats::Scope.

---

bazel/repositories.bzl
tools/code_format/config.yaml

- Update tools/code_format/config.yaml from Envoy's version]
- Update envoy commit version and SHA number.

Update Envoy to 14f2f69 (Jan 30th 2023). 

---

.bazelrc
bazel/repositories.bzl

Updates ubuntu image and envoy_commit/envoy_sha in bazel/repositories.bzl.

Update Envoy to 328fda7 (Feb 27th 2023)

---

bazel/repositories.bzl
ci/run_envoy_docker.sh
tools/code_format/config.yaml

Update Envoy to 2d25a81 (Mar 6th 2023).
- no changes to `.bazelrc`, `.bazelversion`, `tools/gen_compilation_database.py`
- syncing changes in `ci/run_envoy_docker.sh` and `tools/code_format/config.yaml` from the Envoy versions.

Update Envoy to 2d25a81 (Mar 6th 2023).

---

bazel/repositories.bzl
ci/run_envoy_docker.sh
requirements.txt
test/mocks/common/mock_termination_predicate.h

- Imported updates from Envoy's `run_envoy_docker.sh`: https://github.com/envoyproxy/envoy/commit/c62437836b2dd6937c49196928051ae59fc7538e
- Refreshed `requirements.txt`
- No updates in Envoy's:
-  `.bazelrc`
- `.bazelversion`
- `tools/gen_compilation_database.py`
- `tools/code_format/config.yaml`

Update Envoy to 47d28ec (Mar 13, 2023)

---

ci/do_ci.sh

Allows for extraction of binaries built when running inside a Docker container. The `BUILD_DIR` will be mounted to a directory on the host.
Also removes an extra space in the script's help output.

Copy built binaries to a directory when running in Docker.

---

bazel/repositories.bzl
ci/run_envoy_docker.sh
source/common/statistic_impl.h
tools/code_format/config.yaml

- Fix build error `Unimplemented Pure Virtual Method` regarding virtual method `hidden()` introduced in Envoy [19231ba](https://github.com/envoyproxy/envoy/commit/19231ba2b311a115ba85391a18dc73370e1f28d3).
- Sync `ci/run_envoy_docker.sh` and `tools/code_format/config.yaml` from the Envoy repository.

Update Envoy to cab680b (May 26th 2023)

---

README.md
api/client/options.proto
include/nighthawk/client/options.h
source/client/options_impl.cc
source/client/options_impl.h
test/integration/test_integration_basics.py
test/integration/unit_tests/test_utility.py
test/integration/utility.py
test/mocks/client/mock_options.h
test/options_test.cc

Allow disabling default failure predicates.

---

bazel/repositories.bzl
tools/code_format/config.yaml

- no changes to `.bazelrc`, `.bazelversion`, `ci/run_envoy_docker.sh`, `tools/gen_compilation_database.py`.
- synced changes from `tools/code_format/config.yaml`.

Update Envoy to de3ae4a (Jun 9th 2023).

---

bazel/repositories.bzl
requirements.txt
source/client/process_impl.cc

- Update the ENVOY_COMMIT and ENVOY_SHA in [bazel/repositories.bzl](https://github.com/envoyproxy/nighthawk/blob/main/bazel/repositories.bzl) to the latest Envoy's commit.
- Update [requirements.txt](https://github.com/envoyproxy/nighthawk/blob/main/requirements.txt]) with latest python dependencies
- Small function signature change to support compilation with new dependencies

Update Envoy to f97e3d8 (Jun 26th 2023)

---

bazel/repositories.bzl

Update bazel/repositories.bzl with ENVOY_COMMIT and ENVOY_SHA. 
No other update needed.

Update Envoy to 06e3e7d (Jul 28th 2023)

---

.bazelrc
bazel/repositories.bzl
ci/run_envoy_docker.sh
source/adaptive_load/adaptive_load_client_main.cc
source/client/process_impl.cc
test/adaptive_load/adaptive_load_client_main_test.cc
test/output_formatter_test.cc
test/statistic_test.cc

- Update to .bazelrc to https://github.com/envoyproxy/envoy/pull/29874
- Update ci/run_envoy_docker.sh to https://github.com/envoyproxy/envoy/pull/29811
- Update source/client/process_impl.cc to adopt deprecation of `Envoy::Http::Context& httpContext()` in envoy ServerFactoryContext introduced in https://github.com/envoyproxy/envoy/pull/29779
- Update source/adaptive_load/adaptive_load_client_main.cc and a few tests which use `fileReadToEnd` to adopt return type change of `fileReadToEnd` introduced in https://github.com/envoyproxy/envoy/pull/29700

Update Envoy to 7479b6c (Sep 29, 2023)

---

.bazelrc
bazel/repositories.bzl
ci/run_envoy_docker.sh
tools/code_format/config.yaml

Updated nighthawk to envoy commit #6ef1bb4:
- bazel/repositories.bzl
- .bazelrc
- ci/run_envoy_docker.sh
- tools/code_format/config.yaml

Update Envoy to 6ef1bb4 (Oct 13, 2023)

---

.azure-pipelines/pipelines.yml
.bazelrc
bazel/repositories.bzl
ci/run_envoy_docker.sh
requirements.txt
source/client/process_impl.cc

- synced `.bazelrc`, `ci/run_envoy_docker.sh` from Envoy's version.
- no changes in `.bazelversion`, `tools/gen_compilation_database.py`, `tools/code_format/config.yaml`.
- updated Python dependencies in `requirements.txt`.
- added new unimplemented method `NighthawkServerInstance::run` as per the Envoy API change in https://github.com/envoyproxy/envoy/pull/30121.
- froze the docker image at its current version. Our Python tests and checks use on-host Python which has been removed from the Docker image in https://github.com/envoyproxy/envoy-build-tools/pull/290. Going to address this in #1032.

Update Envoy to 7db0b4a (Oct 20th 2023).

---

tools/requirements.txt

Not used since https://github.com/envoyproxy/nighthawk/pull/1033.

Delete requirementx.txt that is no longer in use.

---

tools/base/requirements.in
tools/base/requirements.txt

- removing all unnecessary version pins (which happens to be all the pins).
- updating the lockfile by running `bazel run //tools/base:requirements.update`.
Fixes #1032 
Fixes #935

Updating Python dependencies.

---

.bazelrc
bazel/repositories.bzl
ci/run_envoy_docker.sh
docs/root/updating_envoy_dependency.md
source/client/flush_worker_impl.cc
source/client/flush_worker_impl.h
source/client/process_impl.cc
test/BUILD
test/flush_worker_test.cc
tools/code_format/config.yaml

- synced `.bazelrc`
- synced `bazel/repositories.bzl`
- synced `ci/run_envoy_docker.sh`
- synced `tools/code_format/config.yaml`
- Adjusted Python procedure in `docs/root/updating_envoy_dependency.md`
- Added `ClusterManager` parameter now expected by `FlushWorkerImpl` constructor

Update Envoy to 05457bb (Oct 30, 2023)

---

bazel/repositories.bzl
docs/root/updating_envoy_dependency.md
tools/base/requirements.in

- no changes to `.bazelrc`, `.bazelversion`, `ci/run_envoy_docker.sh`, `tools/gen_compilation_database.py`, `tools/code_format/config.yaml`.
- updated Python requirements in `tools/base/requirements.in`.
- modified Python dependency update instructions - explicitly listing that the date at the top of `tools/base/requirements.in` should be updated.

Update Envoy to acc54c5 (Nov 24th 2023).

---

bazel/repositories.bzl
source/common/BUILD

- updated envoy commit number to 
- updated nighthawk common lib dependency: replace `envoy_common_lib_with_external_headers` with `main_common_lib_with_external_headers`  due to change https://github.com/envoyproxy/envoy/pull/30924/

Update Envoy to 4d154dd(Dec 1st 2023)

---

source/adaptive_load/input_variable_setter_impl.cc
source/adaptive_load/scoring_function_impl.cc
source/adaptive_load/step_controller_impl.cc
source/client/process_impl.cc
source/request_source/request_options_list_plugin_impl.cc
test/adaptive_load/fake_plugins/fake_input_variable_setter/fake_input_variable_setter.cc
test/adaptive_load/fake_plugins/fake_metrics_plugin/fake_metrics_plugin.cc
test/adaptive_load/fake_plugins/fake_step_controller/fake_step_controller.cc
test/adaptive_load/plugin_loader_test.cc
test/request_source/stub_plugin_impl.cc

Nighthawk can use `Envoy::Protobuf::DynamicCastToGenerated` to track Envoy's preferred approach to casting proto `Message`.
See https://github.com/envoyproxy/envoy/blob/e61e461736a28e26b6fcf0ca25d34c47ed29b0fc/source/common/protobuf/protobuf.h#L96

Adopt Envoy::Protobuf::DynamicCastToGenerated

---

.azure-pipelines/pipelines.yml
.bazelrc
bazel/repositories.bzl
ci/do_ci.sh
source/client/process_impl.cc

- Update to .bazelrc to https://github.com/envoyproxy/envoy/pull/31372
- Update source/client/process_impl.cc to support pure virtual function change introduced in https://github.com/envoyproxy/envoy/pull/29289
- Temporarily disable test_gcc target to unblock import. GCC version was updated with new images https://github.com/envoyproxy/envoy/pull/31372 which now fail on various warnings.

Update Envoy to b18ea44 (Dec 18, 2023)

---

.azure-pipelines/pipelines.yml
.bazelrc
bazel/repositories.bzl
source/client/process_impl.cc
source/client/stream_decoder.cc

- Update stream_decoder to support https://github.com/envoyproxy/envoy/pull/31141
- Update source/client/process_impl.cc to support https://github.com/envoyproxy/envoy/pull/31458
- Re-enable test_gcc target to resolve https://github.com/envoyproxy/nighthawk/issues/1049 since we've included https://github.com/envoyproxy/envoy/pull/31470

Update Envoy to cd13b60 (Dec 21, 2023)

---

docs/root/updating_envoy_dependency.md

Our current python dependency update command doesn't update the requirements.txt file when the file has contents.
Removing the contents allows for the it to be written with updated dependencies.

Fix procedure for python dependency updates

---

.bazelrc
bazel/repositories.bzl

- Updates envoy commit id and SHA.
- Updates .bazelrc.

Update Envoy to bb126b8 (Jan 08, 2024)

---

.bazelrc
bazel/repositories.bzl
tools/code_format/config.yaml

- Upstream removed some files from `tools/code_format/config.yaml`
- Trivial `.bazelrc` hash updates
- Trivial `bazel/repositories.bzl` Docker hash updates

Update Envoy to 7d047cd (Jan 16, 2024)

---

bazel/repositories.bzl
tools/code_format/config.yaml

- Update to tools/code_format/config.yaml to https://github.com/envoyproxy/envoy/pull/32022

Update Envoy to 5c821fe (Jan 29, 2024)

---

bazel/repositories.bzl
tools/base/requirements.in
tools/base/requirements.txt

- Updated python dependencies in `tools/base/requirements.in`
- no changes in `.bazelrc`, `.bazelversion`, `ci/run_envoy_docker.sh.`, `tools/gen_compilation_database.py` or `tools/gen_compilation_database.py`

Update Envoy to 14faf9d (Feb 02, 2024)

---

source/adaptive_load/adaptive_load_client_main.cc
source/adaptive_load/adaptive_load_controller_impl.cc
source/client/process_impl.cc
source/client/service_impl.cc
source/common/request_stream_grpc_client_impl.cc
source/common/statistic_impl.cc
source/distributor/nighthawk_distributor_client_impl.cc
source/distributor/service_impl.cc
source/server/configuration.cc
source/sink/service_impl.cc
test/adaptive_load/adaptive_load_client_main_test.cc
test/adaptive_load/adaptive_load_controller_test.cc
test/test_common/proto_matchers.h

The `DebugString` method will be deprecated shortly. Migrating to `absl::StrCat` on the proto messages instead.

Migrate Nighthawk off the proto DebugString method.

---

.bazelrc
bazel/repositories.bzl

- Updated `.bazelrc`
- no changes in `.bazelversion`, `ci/run_envoy_docker.sh.`, `tools/gen_compilation_database.py` or `tools/gen_compilation_database.py`

Update Envoy to 66ed827 (Feb 23, 2024)

---

.bazelrc
bazel/repositories.bzl
source/client/process_impl.cc
source/client/stream_decoder.cc
source/sink/sink_impl.cc
source/user_defined_output/BUILD
tools/base/requirements.in
tools/base/requirements.txt
tools/code_format/config.yaml
tools/gen_compilation_database.py

- Update to .bazelrc and tools/gen_compilation_database.py to https://github.com/envoyproxy/envoy/pull/32585
- Update source/client/process_impl.cc to accommodate refactor in https://github.com/envoyproxy/envoy/pull/32587
- Update tools/code_format/config.yaml for changes in https://github.com/envoyproxy/envoy/pull/32625 and https://github.com/envoyproxy/envoy/pull/32252
- Update python dependencies
- Ensure ostream_formatter definitions are before usage to prevent "explicit specialization of X after instantiation" errors

Update Envoy to e28e0d6 (Mar 05, 2024)

---

.bazelrc
bazel/repositories.bzl
source/client/process_impl.cc
source/server/http_dynamic_delay_filter.cc
source/server/http_dynamic_delay_filter.h
source/server/http_dynamic_delay_filter_config.cc
tools/code_format/config.yaml

- `.bazelrc` updated from upstream
- `tools/code_format/config.yaml` updated from upstream
- In an incredibly confusing refactor:
- Envoy's `FaultFilterConfig` started taking a `CommonFactoryContext` instead of a `Runtime` and `TimeSource`. 
- Updated `HttpDynamicDelayDecoderFilterConfig` to store a `CommonFactoryContext&` instead of a `TimeSource&`, so that it has a `CommonFactoryContext&` to use when constructing a `FaultFilterConfig`.
- How to get a `CommonFactoryContext` when creating the `HttpDynamicDelayDecoderFilterConfig`? `HttpDynamicDelayDecoderFilterConfigFactory` has access to a `Envoy::Server::Configuration::FactoryContext`, which has a `serverFactoryContext()` method. `ServerFactoryContext` is a subclass of `CommonFactoryContext`.
- Envoy has started calling …

Update Envoy to 38c5c86 (Mar 25, 2024)

---

bazel/python_dependencies.bzl
bazel/repositories.bzl
dynamic_config/BUILD
source/adaptive_load/input_variable_setter_impl.cc
source/adaptive_load/scoring_function_impl.cc
source/adaptive_load/step_controller_impl.cc
source/client/process_impl.cc
source/request_source/request_options_list_plugin_impl.cc
source/user_defined_output/log_response_headers_plugin.cc
test/adaptive_load/fake_plugins/fake_input_variable_setter/BUILD
test/adaptive_load/fake_plugins/fake_input_variable_setter/fake_input_variable_setter.cc
test/adaptive_load/fake_plugins/fake_metrics_plugin/BUILD
test/adaptive_load/fake_plugins/fake_metrics_plugin/fake_metrics_plugin.cc
test/adaptive_load/fake_plugins/fake_metrics_plugin/fake_metrics_plugin_test.cc
test/adaptive_load/fake_plugins/fake_step_controller/BUILD
test/adaptive_load/fake_plugins/fake_step_controller/fake_step_controller.cc
test/adaptive_load/plugin_loader_test.cc
test/benchmark_http_client_test.cc
test/dynamic_config/BUILD
test/integration/BUILD
test/integration/unit_tests/BUILD
test/options_test.cc
test/request_source/stub_plugin_impl.cc
test/sink/sink_service_test.cc
test/user_defined_output/fake_plugin/BUILD
test/user_defined_output/fake_plugin/fake_user_defined_output.cc
tools/BUILD
tools/base/BUILD

- No changes to .bazelrc etc.
- Implemented `lifecycleNotifier()` on `NighthawkServerInstance` and `NighthawkServerFactoryContext` (H/T @eziskind for the advance warning and known-good fix)
- Implemented `regexEngine()` on `NighthawkServerFactoryContext`
- Reacted to https://github.com/envoyproxy/envoy/pull/32775
- Renamed `unpackTo` to `unpackToOrThrow`
- Renamed `unpackToNoThrow` to `unpackTo` (the version that returns `Status`)
- `fix_format` reordered some bzl imports and removed unused ones

Update Envoy to 1f52a8e (Mar 29, 2024)

---

.bazelrc
bazel/repositories.bzl
tools/base/requirements.in
tools/base/requirements.txt
tools/code_format/config.yaml

- whitespace-only changes in `.bazelrc`.
- no changes in `.bazelversion`, `ci/run_envoy_docker.sh`, `tools/gen_compilation_database.py`.
- synced changes from Envoy's `tools/code_format/config.yaml`.
- updated Python requirements.

Update Envoy to 01ed2a7 (Apr 5th 20214).

---

bazel/repositories.bzl
source/client/BUILD
source/client/process_impl.cc

- Adjust code to changes in the createTagProducer return value.

Update Envoy to 1ae6fb2 (Apr 8th, 2024)

---

bazel/repositories.bzl
source/client/stream_decoder.h
tools/code_format/config.yaml

- Forced to set `StreamInfoImpl` lifespan explicitly after https://github.com/envoyproxy/envoy/commit/953690a26f20137607ac331fd0232da86f41fcea
-   `FilterState::LifeSpan life_span = FilterState::LifeSpan::FilterChain` was the default we had been using: https://github.com/envoyproxy/envoy/pull/33651/files#diff-621e35bff59bda73d45b8171cab02f360f77bb948d2797936090e5afaee73020

Update Envoy to 9fc5535 (Apr 26, 2024)

---

.bazelrc
bazel/repositories.bzl
tools/code_format/config.yaml

- Update to .bazelrc to https://github.com/envoyproxy/envoy/pull/32022
- Update to tools/code_format/config.yaml to https://github.com/envoyproxy/envoy/pull/33728

Update Envoy to d69544e (May 27, 2024)

---

bazel/repositories.bzl
tools/code_format/config.yaml

- update envoy commit and SHA.
- sync `tools/code_format/config.yaml` from Envoy's version.

Update Envoy to 3feff04 (Jun 28, 2024)

---

bazel/repositories.bzl
tools/base/requirements.in
tools/base/requirements.txt
tools/code_format/config.yaml

- Update python dependencies in `tools/base/requirements.in`
- Update tools/code_format/config.yaml to https://github.com/envoyproxy/envoy/pull/34946

Update Envoy to ab911ac (Jul 08, 2024)

---

source/client/benchmark_client_impl.cc

This is inline with the default connection connect timeout period in 30 seconds. For well behaved clients with short response latencies, this should be a no-op as we will end prematurely once the pool is idle. This does allow for clients with high latencies a long enough time to resolve gracefully.

Increase hard shutdown timeout to 30 seconds

---

bazel/repositories.bzl

No changes needed apart from the new hashes.

Update Envoy to ec75601 (Jul 12, 2024)

---

bazel/python_dependencies.bzl
bazel/repositories.bzl
source/client/process_impl.cc

- Update `@python3_11` to `@python3_12`
- Add `httpServerPropertiesCacheManager()` to `NighthawkServerInstance` (panic only) and `NighthawkServerFactoryContext` (real instance) after https://github.com/envoyproxy/envoy/commit/7b8132ac125d9bd64089d65e3c5396e7aab2fde9

Update Envoy to 9feddc1 (Aug 01, 2024)

---

bazel/repositories.bzl

- Update ENVOY_COMMIT to the latest Envoy's commit.

Update Envoy to ee7991d (Aug 06, 2024)

---

.bazelrc
bazel/repositories.bzl
ci/run_envoy_docker.sh
source/client/process_impl.cc
tools/gen_compilation_database.py

- Update .bazelrc to https://github.com/envoyproxy/envoy/pull/35978
- Update ci/run_envoy_docker.sh to https://github.com/envoyproxy/envoy/pull/35926 and https://github.com/envoyproxy/envoy/pull/35660
- Update tools/gen_compilation_database.py to https://github.com/envoyproxy/envoy/pull/36018 and https://github.com/envoyproxy/envoy/pull/35811
- Update source/client/process_impl.cc to match interface change in https://github.com/envoyproxy/envoy/pull/35912

Update Envoy to fbc6ee2 (Sep 08, 2024)

---

.bazelrc
bazel/repositories.bzl
source/common/request_source_impl.cc
tools/code_format/config.yaml
tools/gen_compilation_database.py

- synced `.bazelrc`, `tools/gen_compilation_database.py`, `tools/code_format/config.yaml` from Envoy's version.
- no changes in `.bazelversion`, `ci/run_envoy_docker.sh`.
- replaced macro `THROW_IF_STATUS_NOT_OK` with `THROW_IF_NOT_OK_REF` as per https://github.com/envoyproxy/envoy/pull/35694.

Update Envoy to 8cd214d (Sep 13th 2024).

---

.bazelrc
bazel/repositories.bzl
source/common/uri_impl.cc
source/exe/BUILD
test/integration/nighthawk_test_server.py
test/process_bootstrap_test.cc
tools/code_format/config.yaml

- Updated `.bazelrc` and `tools/code_format/config.yaml`
- no changes in `ci/run_envoy_docker.sh.`, `.bazelversion`,  or `tools/gen_compilation_database.py`
- Changed external dependencies -> dependencies
- Changed `Envoy::Network::DnsResolver::ResolutionStatus::Success` -> `Envoy::Network::DnsResolver::ResolutionStatus::Completed`
- Added ignore to `internal_address_config is not configured` warning for Test Server

Update Envoy to a93ea37 (Sep 23, 2024)

---

benchmarks/configurations/dynamic_resources_eds.yaml
benchmarks/configurations/envoy_proxy.yaml
benchmarks/configurations/lds.yaml
test/integration/configurations/nighthawk_15_listeners_http_origin.yaml
test/integration/configurations/nighthawk_5_listeners_http_origin.yaml
test/integration/configurations/nighthawk_http_origin.yaml
test/integration/configurations/nighthawk_https_origin.yaml
test/integration/configurations/nighthawk_https_origin_dsa.yaml
test/integration/configurations/nighthawk_https_origin_quic.yaml
test/integration/configurations/nighthawk_track_timings.yaml
test/integration/configurations/sni_origin.yaml
test/integration/nighthawk_test_server.py

Explicitly config internal address config in HTTPConnectionManager
In the next Envoy release, no IP addresses will be considered trusted. 
Therefore, we specify internal address config for each HTTPConnectionManager used in the Nighthawk test servers.

Explicitly config internal address config in HTTPConnectionManager (Sep 24, 2024)

---

.bazelrc
bazel/repositories.bzl
ci/run_envoy_docker.sh
tools/code_format/config.yaml

- Update .bazelrc to https://github.com/envoyproxy/envoy/pull/36438
- Update ci/run_envoy_docker.sh to https://github.com/envoyproxy/envoy/pull/36423
- Update tools/code_format/config.yaml to https://github.com/envoyproxy/envoy/pull/36311

Update Envoy to 33679e4 (Oct 05, 2024)

---

.bazelrc
bazel/repositories.bzl
tools/code_format/config.yaml

1. Update commit number in `bazel/repositories.bzl`.
2. synced changes to `.bazelrc` and `tools/code_format/config.yaml` from Envoy's versions.

Update Envoy to dcbfb85

---

.bazelrc
bazel/repositories.bzl
ci/do_ci.sh
tools/base/requirements.txt

- synced `.bazelrc` from Envoy's version.
- no changes to `.bazelversion`, `ci/run_envoy_docker.sh`, `tools/gen_compilation_database.py`, `tools/code_format/config.yaml`.
- updated Python requirements in `tools/base/requirements.in`.
- lowered coverage threshold from `91.9` to `91.8` due to external changes (no changes to code coverage in this PR).

Update Envoy to 41e0a67 (Dec 2nd 2024).

---

source/adaptive_load/adaptive_load_client_main.cc

This makes the code compatible with a future Protobuf release where various methods return absl::string_view instead of std::string or const std::string&.

Use StrCat for string concatenation

---

source/client/output_formatter_impl.cc

This makes the code compatible with a future Protobuf release where various methods return absl::string_view instead of std::string or const std::string&.

Use AsciiStrToLower to lower-case a string

---

bazel/repositories.bzl
source/common/request_source_impl.cc
tools/base/requirements.in

- Cluster manager `createUncachedRawAsyncClient()` started returning `absl::StatusOr` after https://github.com/envoyproxy/envoy/pull/37765
- Refreshed Python dependencies with `bazel run //tools/base:requirements.update`, but the final `requirements.txt` was identical

Update Envoy to 81cd00f (Jan 10, 2025)

---

bazel/repositories.bzl
source/client/benchmark_client_impl.h
source/client/process_impl.cc
source/server/README.md
test/benchmark_http_client_test.cc
tools/code_format/config.yaml

- no changes in `.bazelrc`, `.bazelversion`, `ci/run_envoy_docker.sh.` or `tools/gen_compilation_database.py`
- APIs for Async Host Resolution were introduced to envoy in https://github.com/envoyproxy/envoy/pull/38021, migrated `HostConstSharedPtr` to `HostSelectionResponse` to match these changes

Update Envoy to 8ded2fe (Jan 18, 2025)

---

api/client/options.proto

Add json_body field to RequestOptions to support dynamic request payloads.
This allows Nighthawk to generate structured request bodies for testing scenarios requiring specific JSON payloads.

Add new field for customizable JSON request body

---

bazel/repositories.bzl
tools/base/requirements.in
tools/base/requirements.txt
tools/code_format/config.yaml

- No code changes needed
- Upstream `tools/code_format/config.yaml` removed some entries
- Refreshed Python dependencies

Update Envoy to dc3b061 (Feb 07, 2025)

---

bazel/repositories.bzl
ci/do_ci.sh
source/client/process_impl.cc
tools/code_format/config.yaml

- no changes in `.bazelrc`, `.bazelversion`, `ci/run_envoy_docker.sh.` or `tools/gen_compilation_database.py`
- `ServerFactoryContext` was extended with `getTransportSocketFactoryContext` in https://github.com/envoyproxy/envoy/pull/38399, extended `NighthawkServerFactoryContext` with `getTransportSocketFactoryContext` to match these changes

Update Envoy to e9398d3 (Feb 14, 2025)

---

test/request_source/BUILD
test/request_source/request_source_plugin_test.cc
test/request_source/test_data/test-jsonconfig-ab.yaml

Split test cases for regular payload and json payload in request_source_plugin_tests.
- Revert the change to test/request_source/test_data/test-config-ab.yaml which added Json_body.
- Create a new config file test/request_source/test_data/test-jsonconfig-ab.yaml.
- Create new tests cases to test config containing Json_body with the new config file.

Split test cases of regular payload and json payload

---

source/request_source/request_options_list_plugin_impl.cc
test/request_source/request_source_plugin_test.cc
test/request_source/test_data/test-jsonconfig-ab.yaml

- If json_body is provided, we should use it to set the content length in request header.
- If json_body is provided, we should set the content type as "application/json" no matter if it is provided in the header.

address content type and content length for json payload

---

source/client/stream_decoder.cc

Pass empty headers to onComplete in case where decodeHeaders was never called.

always pass valid headers to onComplete

---

BUILD
bazel/repositories.bzl

Add `-latomic` and `-lrt`  to fix the CI build after https://github.com/envoyproxy/envoy/pull/38430.

Update Envoy to 78a8841 (Mar 07, 2025)

---

ci/docker/Dockerfile-nighthawk

We had to add `-lrt -latomic` when https://github.com/envoyproxy/nighthawk/pull/1309 updated to the latest Envoy.
https://github.com/envoyproxy/nighthawk/issues/1312 found that the Docker image no longer works because `libatomic.so.1` is not found.
The minimal solution to add `apk install libatomic` was not sufficient to fix the issue because of unknown Alpine issues.
Migrating from Alpine to Ubuntu 22.04 and including `RUN apt-get update && apt-get install libatomic1` appears to work. (Ubuntu SHA is copied from Envoy: https://github.com/envoyproxy/envoy/blob/f2023ef77bdb4abaf9feef963c9a0c291f55568f/ci/Dockerfile-envoy)
Just changing the `FROM` to Ubuntu 22.04, before adding `apt-get install libatomic1`, we start off with a similar error:
```
ci/do_ci.sh docker
docker run …
```

migrate Nighthawk Docker image from Alpine to Ubuntu

---

bazel/repositories.bzl
source/client/process_impl.cc
tools/code_format/config.yaml

- no changes in `.bazelrc`, `.bazelversion`, `ci/run_envoy_docker.sh.` or `tools/gen_compilation_database.py`
- Deduped `NighthawkServerFactoryContext ` into `NighthawkServerInstance ` so that we can successfully call xdsManager() from NighthawkServerFactoryContext. Necessary due to https://github.com/envoyproxy/envoy/pull/38792, which added Instance parameter into xDS Manager.

Update Envoy to 108dd56 (Mar 24, 2025)

---

source/client/process_impl.cc
test/integration/test_integration_basics.py

This is required when validation_context is used in transport socket.
Fixes #1338.

Provide a valid instance of secretManager.

---

.azure-pipelines/pipelines.yml
.bazelrc
ci/do_ci.sh

Explicitly select `libc++` now that we are using Bazel's hermetic SAN libraries.

Re-enable TSAN in CI with a fix.

---

bazel/repositories.bzl

Update `ENVOY_COMMIT` and `ENVOY_SHA`.

Update Envoy to 25037e7 (Jun 23, 2025)

---

bazel/repositories.bzl

No updates except `ENVOY_COMMIT` and `ENVOY_SHA`.

Update Envoy to 1f468dd (Jul 18, 2025)

---

docs/root/updating_envoy_dependency.md

The auto script gave me some unexpected results -- leading me to investigate failures which do not come from ci build / test or merge conflicts. I suspect there are still some improvements needed or bugs to be fixed in the auto workflow. So, until we get enough confidence and less use of frictions in the auto workflow, let's keep the manual update instruction which has been working well.

restore the manual updating envoy dependency instruction

---

README.md
api/client/options.proto
source/client/factories_impl.cc
source/client/output_formatter_impl.cc
source/client/output_formatter_impl.h
test/BUILD
test/output_formatter_test.cc
test/test_data/output_formatter.prometheus.gold

See commit message for more details.
This Pull Request adds support for `prometheus` output-format support to `nighthawk_client` and `nighthawk_output_transform`.
Example Usage:
```bash
nighthawk_client http://httpbin.org/ --output-format prometheus
nighthawk_client http://httpbin.org/ --output-format prometheus -v critical | \
curl --data-binary @- \
"http://<prom-pushgateway>/metrics/job/http-benchmark/instance/test"
nighthawk_client http://httpbin.org/ --output-format json -v critical | \
nighthawk_output_transform --output-format prometheus
```
Prometheus output format emits nighthawk result counters as prometheus `counters` and statistics as `summary`.

Add prometheus output format support for nighthawk_client

---

ci/docker/docker_push.sh

When using nighthawk docker image it would be helpful for downstream consumers to have a stable tag for reference instead of rely on `latest`.

ci: push nighthawk images tagged with Github SHA

---

docs/root/updating_envoy_dependency.md
tools/nighthawk_envoy_updater.py

Addressing usability concerns and bugs noticed in use:
- Run `bazel clean --expunge` before running through Envoy commits; one integration attempt failed because of a messy workspace rather than any actual problem with the Envoy commit.
- Remove the `--gpg-sign` flag from the `git commit` step, which is not required by the Nighthawk repo.
- Update the handling for a mixed case bisection result (some passing, some failing) to ensure the generated temporary commit applies the latest _passing_ Envoy commit. Previously, in the case where the bisection runs a failing commit as its last attempt, the utility wouldn't revert state to the last-known-good commit integration.
- Remove `x` from repo cleanup step to preserve .gitignore files.
- Update manual Envoy update docs to remove version pinning …

Address bugs in updater utility: Bazel clean, remove --gpg-sign, commit last-known-good in mixed case
